import type { Locale } from "./i18n";

/**
 * Перевод содержимого — того, что вводит редактор, а не печатает код.
 *
 * Интерфейс переведён в i18n.ts. Здесь — встроенные данные: категории
 * мест, города, теги, кухни, советы, уведомления. Ключ словаря — сама
 * русская строка из данных; перевода нет — отдаём её как есть.
 *
 * Так новый материал, введённый в панели, не ломается: для него перевода
 * в словаре просто не найдётся, и он покажется на языке ввода. Настоящая
 * многоязычность содержимого — это отдельные поля на каждый язык в самой
 * записи; она появится, когда редактор будет вводить переводы. Пока же
 * переведено то, что заложено в приложение изначально.
 *
 * Имена-топонимы (Регистан, Гур-э-Амир) сознательно не трогаем: их люди
 * так и ищут, а коверкать по чужим алфавитам «на глаз» — та же ложь, что
 * и рисовать границу по памяти. Переводим то, что переводится точно:
 * категории и общие слова.
 */

type Строка = Partial<Record<Locale, string>>;

/** en опускаем там, где он совпадает с оригиналом; ru — это сам ключ. */
function с(
  ключ: string,
  переводы: Строка,
): [string, Строка] {
  return [ключ, переводы];
}

const ЗАПИСИ: [string, Строка][] = [
  // ── Категории мест ───────────────────────────────────────────────
  с("История", { en: "History", uz: "Tarix", zh: "历史", ko: "역사", de: "Geschichte", fr: "Histoire", ja: "歴史", tr: "Tarih", ar: "التاريخ" }),
  с("Мечеть", { en: "Mosque", uz: "Masjid", zh: "清真寺", ko: "모스크", de: "Moschee", fr: "Mosquée", ja: "モスク", tr: "Cami", ar: "مسجد" }),
  с("Музей", { en: "Museum", uz: "Muzey", zh: "博物馆", ko: "박물관", de: "Museum", fr: "Musée", ja: "博物館", tr: "Müze", ar: "متحف" }),
  с("Природа", { en: "Nature", uz: "Tabiat", zh: "自然", ko: "자연", de: "Natur", fr: "Nature", ja: "自然", tr: "Doğa", ar: "الطبيعة" }),
  с("Базары", { en: "Bazaar", uz: "Bozor", zh: "集市", ko: "시장", de: "Basar", fr: "Bazar", ja: "バザール", tr: "Pazar", ar: "سوق" }),
  с("Крепость", { en: "Fortress", uz: "Qal'a", zh: "城堡", ko: "요새", de: "Festung", fr: "Forteresse", ja: "要塞", tr: "Kale", ar: "قلعة" }),
  с("Мавзолей", { en: "Mausoleum", uz: "Maqbara", zh: "陵墓", ko: "영묘", de: "Mausoleum", fr: "Mausolée", ja: "霊廟", tr: "Türbe", ar: "ضريح" }),
  с("Минарет", { en: "Minaret", uz: "Minora", zh: "宣礼塔", ko: "미너렛", de: "Minarett", fr: "Minaret", ja: "ミナレット", tr: "Minare", ar: "مئذنة" }),
  с("Площадь", { en: "Square", uz: "Maydon", zh: "广场", ko: "광장", de: "Platz", fr: "Place", ja: "広場", tr: "Meydan", ar: "ساحة" }),
  с("Старый город", { en: "Old town", uz: "Eski shahar", zh: "古城", ko: "구시가지", de: "Altstadt", fr: "Vieille ville", ja: "旧市街", tr: "Eski şehir", ar: "المدينة القديمة" }),
  с("Обычный", { en: "Place", uz: "Oddiy", zh: "地点", ko: "일반", de: "Ort", fr: "Lieu", ja: "スポット", tr: "Yer", ar: "مكان" }),
  с("Скоростной", { en: "Express", uz: "Tezyurar", zh: "高速", ko: "고속", de: "Schnell", fr: "Express", ja: "特急", tr: "Hızlı", ar: "سريع" }),

  // ── Города ───────────────────────────────────────────────────────
  с("Ташкент", { en: "Tashkent", uz: "Toshkent", zh: "塔什干", ko: "타슈켄트", de: "Taschkent", fr: "Tachkent", ja: "タシケント", tr: "Taşkent", ar: "طشقند" }),
  с("Самарканд", { en: "Samarkand", uz: "Samarqand", zh: "撒马尔罕", ko: "사마르칸트", de: "Samarkand", fr: "Samarcande", ja: "サマルカンド", tr: "Semerkant", ar: "سمرقند" }),
  с("Бухара", { en: "Bukhara", uz: "Buxoro", zh: "布哈拉", ko: "부하라", de: "Buchara", fr: "Boukhara", ja: "ブハラ", tr: "Buhara", ar: "بخارى" }),
  с("Хива", { en: "Khiva", uz: "Xiva", zh: "希瓦", ko: "히바", de: "Chiwa", fr: "Khiva", ja: "ヒヴァ", tr: "Hive", ar: "خيوة" }),
  с("Нукус", { en: "Nukus", uz: "Nukus", zh: "努库斯", ko: "누쿠스", de: "Nukus", fr: "Noukous", ja: "ヌクス", tr: "Nukus", ar: "نوكوس" }),
  с("Фергана", { en: "Fergana", uz: "Fargʻona", zh: "费尔干纳", ko: "페르가나", de: "Fergana", fr: "Ferghana", ja: "フェルガナ", tr: "Fergana", ar: "فرغانة" }),
  с("Наманган", { en: "Namangan", uz: "Namangan", zh: "纳曼干", ko: "나망간", de: "Namangan", fr: "Namangan", ja: "ナマンガン", tr: "Namangan", ar: "نمنغان" }),
  с("Андижан", { en: "Andijan", uz: "Andijon", zh: "安集延", ko: "안디잔", de: "Andijan", fr: "Andijan", ja: "アンディジャン", tr: "Andican", ar: "أنديجان" }),
  с("Термез", { en: "Termez", uz: "Termiz", zh: "铁尔梅兹", ko: "테르메즈", de: "Termiz", fr: "Termez", ja: "テルメズ", tr: "Termez", ar: "ترمذ" }),
  с("Карши", { en: "Karshi", uz: "Qarshi", zh: "卡尔希", ko: "카르시", de: "Karshi", fr: "Karchi", ja: "カルシ", tr: "Karşı", ar: "قرشي" }),
  с("Гулистан", { en: "Gulistan", uz: "Guliston", zh: "古利斯坦", ko: "굴리스탄", de: "Gulistan", fr: "Goulistan", ja: "グリスタン", tr: "Gülistan", ar: "غولستان" }),
  с("Джизак", { en: "Jizzakh", uz: "Jizzax", zh: "吉扎克", ko: "지자흐", de: "Dschizak", fr: "Djizak", ja: "ジザフ", tr: "Cizzah", ar: "جيزاك" }),
  с("Чарвак", { en: "Charvak", uz: "Chorvoq", zh: "恰尔瓦克", ko: "차르바크", de: "Tscharwak", fr: "Tcharvak", ja: "チャルヴァク", tr: "Çarvak", ar: "تشارفاك" }),

  // ── Теги отелей ──────────────────────────────────────────────────
  с("Люкс", { en: "Luxury", uz: "Hashamatli", zh: "豪华", ko: "럭셔리", de: "Luxus", fr: "Luxe", ja: "ラグジュアリー", tr: "Lüks", ar: "فاخر" }),
  с("Бутик", { en: "Boutique", uz: "Butik", zh: "精品", ko: "부티크", de: "Boutique", fr: "Boutique", ja: "ブティック", tr: "Butik", ar: "بوتيك" }),
  с("Популярный", { en: "Popular", uz: "Mashhur", zh: "热门", ko: "인기", de: "Beliebt", fr: "Populaire", ja: "人気", tr: "Popüler", ar: "شائع" }),
  с("Панорама", { en: "Panorama", uz: "Panorama", zh: "全景", ko: "파노라마", de: "Panorama", fr: "Panorama", ja: "パノラマ", tr: "Panorama", ar: "بانوراما" }),
  с("Лучшая цена", { en: "Best price", uz: "Eng yaxshi narx", zh: "最优价格", ko: "최저가", de: "Bester Preis", fr: "Meilleur prix", ja: "最安値", tr: "En iyi fiyat", ar: "أفضل سعر" }),
  с("Топ выбор", { en: "Top choice", uz: "Eng yaxshi tanlov", zh: "首选", ko: "최고 추천", de: "Top-Wahl", fr: "Choix n°1", ja: "イチオシ", tr: "En iyi seçim", ar: "الخيار الأفضل" }),
  с("Хит", { en: "Hit", uz: "Xit", zh: "热销", ko: "인기", de: "Hit", fr: "Populaire", ja: "話題", tr: "Gözde", ar: "الأكثر رواجاً" }),

  // ── Кухни ────────────────────────────────────────────────────────
  с("Узбекская", { en: "Uzbek", uz: "Oʻzbek", zh: "乌兹别克菜", ko: "우즈베크", de: "Usbekisch", fr: "Ouzbèke", ja: "ウズベク料理", tr: "Özbek", ar: "أوزبكي" }),
  с("Традиционная", { en: "Traditional", uz: "Anʼanaviy", zh: "传统菜", ko: "전통", de: "Traditionell", fr: "Traditionnel", ja: "伝統料理", tr: "Geleneksel", ar: "تقليدي" }),
  с("Гриль", { en: "Grill", uz: "Gril", zh: "烧烤", ko: "그릴", de: "Grill", fr: "Grill", ja: "グリル", tr: "Izgara", ar: "مشويات" }),

  // ── Советы для туристов ──────────────────────────────────────────
  с("Курс смотрите в конвертере выше — он живой", { en: "See the live rate in the converter above", uz: "Kursni yuqoridagi konvertorda koʻring — u jonli", zh: "上方转换器为实时汇率", ko: "위 계산기에서 실시간 환율 확인", de: "Aktuellen Kurs im Rechner oben ansehen", fr: "Le taux en direct est dans le convertisseur ci-dessus", ja: "上の換算ツールでリアルタイムのレートを確認", tr: "Güncel kuru yukarıdaki çeviricide görün", ar: "اطّلع على السعر الحيّ في المحوّل أعلاه" }),
  с("Обменивайте в банках или обменниках", { en: "Exchange at banks or exchange offices", uz: "Bank yoki almashtirish shoxobchalarida ayirboshlang", zh: "在银行或兑换点换汇", ko: "은행이나 환전소에서 환전", de: "In Banken oder Wechselstuben tauschen", fr: "Changez dans les banques ou bureaux de change", ja: "銀行か両替所で両替を", tr: "Banka veya döviz bürolarında bozdurun", ar: "بدّل في البنوك أو مكاتب الصرافة" }),
  с("Карты принимают в крупных отелях", { en: "Cards are accepted in large hotels", uz: "Kartalar yirik mehmonxonalarda qabul qilinadi", zh: "大型酒店可刷卡", ko: "대형 호텔은 카드 결제 가능", de: "Karten werden in großen Hotels akzeptiert", fr: "Les cartes sont acceptées dans les grands hôtels", ja: "大きなホテルではカードが使えます", tr: "Büyük otellerde kart geçer", ar: "تُقبل البطاقات في الفنادق الكبيرة" }),
  с("Наличные нужны для рынков и кафе", { en: "You'll need cash for markets and cafes", uz: "Bozor va kafelar uchun naqd pul kerak", zh: "市场和咖啡馆需备现金", ko: "시장·카페는 현금 필요", de: "Für Märkte und Cafés brauchen Sie Bargeld", fr: "Prévoyez du liquide pour marchés et cafés", ja: "市場やカフェは現金が必要", tr: "Pazar ve kafeler için nakit gerekir", ar: "تحتاج نقداً للأسواق والمقاهي" }),
  с("Яндекс.Такси — самый удобный", { en: "Yandex Taxi is the most convenient", uz: "Yandex Taksi eng qulayi", zh: "Yandex 打车最方便", ko: "얀덱스 택시가 가장 편리", de: "Yandex Taxi ist am bequemsten", fr: "Yandex Taxi est le plus pratique", ja: "Yandexタクシーが最も便利", tr: "En pratiği Yandex Taksi", ar: "تطبيق Yandex Taxi هو الأسهل" }),
  с("Афросиаб: Ташкент–Самарканд 2 ч $12", { en: "Afrosiyob: Tashkent–Samarkand 2 h $12", uz: "Afrosiyob: Toshkent–Samarqand 2 soat $12", zh: "阿夫罗夏布号：塔什干—撒马尔罕 2小时 $12", ko: "아프로시욥: 타슈켄트–사마르칸트 2시간 $12", de: "Afrosiyob: Taschkent–Samarkand 2 Std. 12 $", fr: "Afrosiyob : Tachkent–Samarcande 2 h 12 $", ja: "アフロシヨブ号：タシケント–サマルカンド2時間 $12", tr: "Afrosiyob: Taşkent–Semerkant 2 sa $12", ar: "أفروسياب: طشقند–سمرقند ساعتان 12$" }),
  с("Самарканд–Бухара 1.5 ч $9", { en: "Samarkand–Bukhara 1.5 h $9", uz: "Samarqand–Buxoro 1,5 soat $9", zh: "撒马尔罕—布哈拉 1.5小时 $9", ko: "사마르칸트–부하라 1.5시간 $9", de: "Samarkand–Buchara 1,5 Std. 9 $", fr: "Samarcande–Boukhara 1,5 h 9 $", ja: "サマルカンド–ブハラ1.5時間 $9", tr: "Semerkant–Buhara 1,5 sa $9", ar: "سمرقند–بخارى 1.5 ساعة 9$" }),
  с("Метро есть только в Ташкенте", { en: "The metro exists only in Tashkent", uz: "Metro faqat Toshkentda bor", zh: "地铁仅塔什干有", ko: "지하철은 타슈켄트에만 있음", de: "U-Bahn gibt es nur in Taschkent", fr: "Le métro n'existe qu'à Tachkent", ja: "地下鉄はタシケントのみ", tr: "Metro yalnızca Taşkent'te var", ar: "المترو موجود في طشقند فقط" }),
  с("Аренда авто от $30/день", { en: "Car rental from $30/day", uz: "Avto ijara $30/kundan", zh: "租车 $30/天起", ko: "렌터카 하루 $30부터", de: "Mietwagen ab 30 $/Tag", fr: "Location de voiture dès 30 $/jour", ja: "レンタカー1日 $30～", tr: "Araç kirası günlük 30$'dan", ar: "تأجير سيارة من 30$ يومياً" }),
  с("Апрель–июнь: +20–28°C — идеально", { en: "April–June: +20–28°C — ideal", uz: "Aprel–iyun: +20–28°C — ideal", zh: "四至六月：+20–28°C，最佳", ko: "4~6월: +20–28°C — 최적", de: "April–Juni: +20–28 °C — ideal", fr: "Avril–juin : +20–28 °C — idéal", ja: "4〜6月：+20〜28°C 最適", tr: "Nisan–Haziran: +20–28°C — ideal", ar: "أبريل–يونيو: +20–28° مثالي" }),
  с("Сентябрь–октябрь: +22–30°C", { en: "September–October: +22–30°C", uz: "Sentabr–oktabr: +22–30°C", zh: "九至十月：+22–30°C", ko: "9~10월: +22–30°C", de: "September–Oktober: +22–30 °C", fr: "Septembre–octobre : +22–30 °C", ja: "9〜10月：+22〜30°C", tr: "Eylül–Ekim: +22–30°C", ar: "سبتمبر–أكتوبر: +22–30°" }),
  с("Июль–август: +35–42°C — зной", { en: "July–August: +35–42°C — very hot", uz: "Iyul–avgust: +35–42°C — jazirama", zh: "七至八月：+35–42°C，酷热", ko: "7~8월: +35–42°C — 무더위", de: "Juli–August: +35–42 °C — Hitze", fr: "Juillet–août : +35–42 °C — canicule", ja: "7〜8月：+35〜42°C 猛暑", tr: "Temmuz–Ağustos: +35–42°C — sıcak", ar: "يوليو–أغسطس: +35–42° حرّ شديد" }),
  с("Берите головной убор и крем", { en: "Bring a hat and sunscreen", uz: "Bosh kiyim va krem oling", zh: "备好帽子和防晒霜", ko: "모자와 자외선 차단제 준비", de: "Hut und Sonnencreme mitnehmen", fr: "Prenez chapeau et crème solaire", ja: "帽子と日焼け止めを", tr: "Şapka ve güneş kremi alın", ar: "خذ قبعة وواقي شمس" }),
  с("Ucell и Beeline — лучшее покрытие", { en: "Ucell and Beeline have the best coverage", uz: "Ucell va Beeline — eng yaxshi qamrov", zh: "Ucell 和 Beeline 信号最佳", ko: "Ucell·Beeline 커버리지 최고", de: "Ucell und Beeline haben beste Abdeckung", fr: "Ucell et Beeline : meilleure couverture", ja: "UcellとBeelineが最も繋がる", tr: "En iyi kapsama Ucell ve Beeline", ar: "Ucell وBeeline الأفضل تغطية" }),
  с("SIM-карта: ~$5, нужен паспорт", { en: "SIM card: ~$5, passport required", uz: "SIM-karta: ~$5, pasport kerak", zh: "SIM卡约$5，需护照", ko: "유심 약 $5, 여권 필요", de: "SIM-Karte: ca. 5 $, Pass nötig", fr: "Carte SIM : ~5 $, passeport requis", ja: "SIMカード：約$5、パスポート必要", tr: "SIM kart: ~$5, pasaport gerekli", ar: "شريحة SIM: ~5$، يلزم جواز السفر" }),
  с("Безлимитный интернет от $3/мес", { en: "Unlimited internet from $3/month", uz: "Cheksiz internet $3/oydan", zh: "无限流量 $3/月起", ko: "무제한 인터넷 월 $3부터", de: "Unbegrenztes Internet ab 3 $/Monat", fr: "Internet illimité dès 3 $/mois", ja: "無制限ネット 月$3～", tr: "Sınırsız internet aylık 3$'dan", ar: "إنترنت غير محدود من 3$ شهرياً" }),
  с("Wi-Fi бесплатно в отелях", { en: "Wi-Fi is free in hotels", uz: "Mehmonxonalarda Wi-Fi bepul", zh: "酒店提供免费 Wi-Fi", ko: "호텔 와이파이 무료", de: "WLAN in Hotels kostenlos", fr: "Wi-Fi gratuit dans les hôtels", ja: "ホテルのWi-Fiは無料", tr: "Otellerde Wi-Fi ücretsiz", ar: "الواي فاي مجاني في الفنادق" }),
  с("В мечетях — скромная одежда", { en: "Dress modestly in mosques", uz: "Masjidlarda kamtarona kiyim", zh: "清真寺着装需端庄", ko: "모스크에서는 단정한 복장", de: "In Moscheen dezente Kleidung", fr: "Tenue modeste dans les mosquées", ja: "モスクでは控えめな服装を", tr: "Camilerde sade giyim", ar: "ارتدِ ملابس محتشمة في المساجد" }),
  с("Снимайте обувь перед входом", { en: "Take off shoes before entering", uz: "Kirishdan oldin poyabzalni yeching", zh: "进门前请脱鞋", ko: "입장 전 신발 벗기", de: "Vor dem Eintritt Schuhe ausziehen", fr: "Retirez vos chaussures avant d'entrer", ja: "入る前に靴を脱ぐ", tr: "Girmeden önce ayakkabıları çıkarın", ar: "اخلع حذاءك قبل الدخول" }),
  с("Спрашивайте перед фото людей", { en: "Ask before photographing people", uz: "Odamlarni suratga olishdan oldin soʻrang", zh: "拍人前先征得同意", ko: "사람 촬영 전 허락 구하기", de: "Vor Personenfotos um Erlaubnis fragen", fr: "Demandez avant de photographier les gens", ja: "人を撮る前に一言を", tr: "İnsanları çekmeden önce sorun", ar: "استأذن قبل تصوير الناس" }),
  с("Левая рука считается нечистой", { en: "The left hand is considered unclean", uz: "Chap qoʻl nopok hisoblanadi", zh: "左手被视为不洁", ko: "왼손은 부정하게 여겨짐", de: "Die linke Hand gilt als unrein", fr: "La main gauche est jugée impure", ja: "左手は不浄とされる", tr: "Sol el kirli sayılır", ar: "اليد اليسرى تُعدّ غير طاهرة" }),
  с("Чаевые 5–10% — не обязательны", { en: "Tips 5–10% — optional", uz: "Choychaqa 5–10% — majburiy emas", zh: "小费 5–10%，非强制", ko: "팁 5–10% — 선택", de: "Trinkgeld 5–10 % — freiwillig", fr: "Pourboire 5–10 % — facultatif", ja: "チップ5〜10%（任意）", tr: "Bahşiş %5–10 — isteğe bağlı", ar: "بقشيش 5–10% اختياري" }),
  с("Пейте бутилированную воду", { en: "Drink bottled water", uz: "Shishadagi suv iching", zh: "请喝瓶装水", ko: "생수를 드세요", de: "Trinken Sie Flaschenwasser", fr: "Buvez de l'eau en bouteille", ja: "ボトル入りの水を", tr: "Şişe suyu için", ar: "اشرب مياهاً معبأة" }),
  с("Скорая: 103, Полиция: 102", { en: "Ambulance: 103, Police: 102", uz: "Tez yordam: 103, Politsiya: 102", zh: "急救：103，警察：102", ko: "구급 103, 경찰 102", de: "Rettung: 103, Polizei: 102", fr: "Ambulance : 103, Police : 102", ja: "救急:103、警察:102", tr: "Ambulans: 103, Polis: 102", ar: "الإسعاف 103، الشرطة 102" }),
  с("Туристический инфолайн: 1322", { en: "Tourist infoline: 1322", uz: "Turistik infoliniya: 1322", zh: "旅游热线：1322", ko: "관광 안내전화 1322", de: "Touristen-Hotline: 1322", fr: "Ligne info tourisme : 1322", ja: "観光インフォライン:1322", tr: "Turist hattı: 1322", ar: "خط معلومات السياحة: 1322" }),
  с("Страховка для путешественников", { en: "Travel insurance", uz: "Sayohatchilar uchun sugʻurta", zh: "旅行保险", ko: "여행자 보험", de: "Reiseversicherung", fr: "Assurance voyage", ja: "旅行保険", tr: "Seyahat sigortası", ar: "تأمين السفر" }),
  с("Плов — главное блюдо, до полудня", { en: "Plov is the main dish, before noon", uz: "Osh — asosiy taom, tushgacha", zh: "抓饭是招牌，午前享用", ko: "플로프는 대표 음식, 정오 전", de: "Plov ist das Hauptgericht, vormittags", fr: "Le plov, plat phare, avant midi", ja: "プロフは名物、正午前に", tr: "Plov ana yemek, öğleden önce", ar: "البلوف الطبق الرئيسي، قبل الظهر" }),
  с("Самса, лагман, шашлык, нон", { en: "Samsa, lagman, shashlik, non", uz: "Somsa, lagʻmon, shashlik, non", zh: "萨姆萨、拉条子、烤肉、囊", ko: "삼사·라그만·샤슬릭·논", de: "Samsa, Lagman, Schaschlik, Non", fr: "Samsa, laghman, chachlik, non", ja: "サムサ、ラグマン、シャシリク、ノン", tr: "Somsa, lağman, şaşlık, non", ar: "سمسة، لغمان، شواء، خبز نون" }),
  с("Базары: Чорсу (Ташкент), Сиаб (Самарканд)", { en: "Bazaars: Chorsu (Tashkent), Siab (Samarkand)", uz: "Bozorlar: Chorsu (Toshkent), Siyob (Samarqand)", zh: "集市：乔尔苏（塔什干）、夏布（撒马尔罕）", ko: "시장: 초르수(타슈켄트), 시압(사마르칸트)", de: "Basare: Chorsu (Taschkent), Siab (Samarkand)", fr: "Bazars : Chorsu (Tachkent), Siab (Samarcande)", ja: "バザール：チョルスー（タシケント）、シアブ（サマルカンド）", tr: "Pazarlar: Çorsu (Taşkent), Siab (Semerkant)", ar: "أسواق: تشورسو (طشقند)، سياب (سمرقند)" }),
  с("Вегетарианцам: мастава, дамлама", { en: "Vegetarians: mastava, damlama", uz: "Vegetarianlarga: mastava, damlama", zh: "素食：马斯塔瓦、达姆拉马", ko: "채식: 마스타바, 담라마", de: "Vegetarisch: Mastawa, Damlama", fr: "Végétariens : mastava, damlama", ja: "ベジタリアン向け：マスタバ、ダムラマ", tr: "Vejetaryenlere: mastava, damlama", ar: "للنباتيين: ماستافا، دملمة" }),
  с("Тип C и F, 220В, 50Гц", { en: "Type C and F, 220V, 50Hz", uz: "C va F turi, 220V, 50Hz", zh: "C/F型，220V，50Hz", ko: "C·F형, 220V, 50Hz", de: "Typ C und F, 220 V, 50 Hz", fr: "Type C et F, 220 V, 50 Hz", ja: "CタイプとFタイプ、220V、50Hz", tr: "Tip C ve F, 220V, 50Hz", ar: "نوع C وF، 220 فولت، 50 هرتز" }),
  с("Адаптер нужен гостям из США/UK", { en: "Guests from US/UK need an adapter", uz: "AQSh/Britaniya mehmonlariga adapter kerak", zh: "美/英游客需转换插头", ko: "미국·영국 방문객은 어댑터 필요", de: "Gäste aus USA/UK brauchen Adapter", fr: "Les visiteurs US/UK ont besoin d'un adaptateur", ja: "米英からの方はアダプター必要", tr: "ABD/İngiltere'den gelenlere adaptör gerekir", ar: "زوّار أمريكا/بريطانيا يحتاجون مهايئاً" }),
  с("Качество электричества стабильное", { en: "Power quality is stable", uz: "Elektr sifati barqaror", zh: "供电稳定", ko: "전력 품질 안정", de: "Stromqualität ist stabil", fr: "La qualité du courant est stable", ja: "電力供給は安定", tr: "Elektrik kalitesi istikrarlı", ar: "جودة الكهرباء مستقرة" }),
  // ── Уведомления ──────────────────────────────────────────────────
  с("Вы рядом с Регистаном", { en: "You're near the Registan", uz: "Registon yaqinidasiz", zh: "您在雷吉斯坦附近", ko: "레기스탄 근처입니다", de: "Sie sind nahe dem Registan", fr: "Vous êtes près du Registan", ja: "レギスタン広場の近くです", tr: "Registan'a yakınsınız", ar: "أنت قرب ريغستان" }),
  с("Нажмите, чтобы включить аудиогид — 8 мин истории.", { en: "Tap to start the audio guide — 8 min of history.", uz: "Audio yoʻriqchini yoqish uchun bosing — 8 daqiqa tarix.", zh: "点击开启语音导览 — 8分钟历史。", ko: "눌러서 오디오 가이드 시작 — 8분 역사.", de: "Tippen für den Audioguide — 8 Min. Geschichte.", fr: "Touchez pour l'audioguide — 8 min d'histoire.", ja: "タップで音声ガイド開始 — 歴史8分。", tr: "Sesli rehber için dokunun — 8 dk tarih.", ar: "اضغط لبدء الدليل الصوتي — 8 دقائق تاريخ." }),
  с("Световое шоу сегодня", { en: "Light show today", uz: "Bugun yorugʻlik shousi", zh: "今晚灯光秀", ko: "오늘 라이트 쇼", de: "Lichtshow heute", fr: "Spectacle de lumière aujourd'hui", ja: "今夜ライトショー", tr: "Bugün ışık gösterisi", ar: "عرض ضوئي اليوم" }),
  с("Регистан · 21:00 · Билеты от $10. Осталось 12 мест!", { en: "Registan · 21:00 · Tickets from $10. 12 seats left!", uz: "Registon · 21:00 · Chiptalar $10 dan. 12 joy qoldi!", zh: "雷吉斯坦 · 21:00 · 门票$10起，仅剩12座！", ko: "레기스탄 · 21:00 · 티켓 $10부터. 12석 남음!", de: "Registan · 21:00 · Tickets ab 10 $. Noch 12 Plätze!", fr: "Registan · 21:00 · Billets dès 10 $. 12 places restantes !", ja: "レギスタン · 21:00 · チケット$10～。残り12席！", tr: "Registan · 21:00 · Bilet 10$'dan. 12 yer kaldı!", ar: "ريغستان · 21:00 · التذاكر من 10$. بقي 12 مقعداً!" }),
  с("Скидка 15% на отели", { en: "15% off hotels", uz: "Mehmonxonalarga 15% chegirma", zh: "酒店 85 折", ko: "호텔 15% 할인", de: "15 % Rabatt auf Hotels", fr: "-15 % sur les hôtels", ja: "ホテル15%オフ", tr: "Otellerde %15 indirim", ar: "خصم 15% على الفنادق" }),
  с("Код UZUP15 до 31 авг.", { en: "Code UZUP15 until Aug 31.", uz: "UZUP15 kodi 31 avgustgacha.", zh: "优惠码 UZUP15，8月31日前有效。", ko: "코드 UZUP15, 8월 31일까지.", de: "Code UZUP15 bis 31. Aug.", fr: "Code UZUP15 jusqu'au 31 août.", ja: "コードUZUP15、8月31日まで。", tr: "UZUP15 kodu 31 Ağustos'a kadar.", ar: "الرمز UZUP15 حتى 31 أغسطس." }),
  с("Маршрут завершён!", { en: "Route completed!", uz: "Marshrut yakunlandi!", zh: "路线已完成！", ko: "경로 완료!", de: "Route abgeschlossen!", fr: "Itinéraire terminé !", ja: "ルート完了！", tr: "Rota tamamlandı!", ar: "اكتمل المسار!" }),
  с("«Самарканд за 1 день» — получите штамп!", { en: "‘Samarkand in 1 day’ — get your stamp!", uz: "«Samarqand 1 kunda» — muhr oling!", zh: "《一日撒马尔罕》— 领取印章！", ko: "'하루 사마르칸트' — 스탬프 받기!", de: "„Samarkand an 1 Tag“ — Stempel holen!", fr: "« Samarcande en 1 jour » — obtenez le tampon !", ja: "「1日サマルカンド」— スタンプ獲得！", tr: "'1 Günde Semerkant' — damganı al!", ar: "«سمرقند في يوم» — احصل على ختمك!" }),
  с("Новый аудиогид", { en: "New audio guide", uz: "Yangi audio yoʻriqchi", zh: "新语音导览", ko: "새 오디오 가이드", de: "Neuer Audioguide", fr: "Nouvel audioguide", ja: "新しい音声ガイド", tr: "Yeni sesli rehber", ar: "دليل صوتي جديد" }),
  с("Гур-э-Амир · Обновлённая версия.", { en: "Gur-e-Amir · Updated version.", uz: "Goʻri Amir · Yangilangan versiya.", zh: "古尔-埃米尔 · 更新版。", ko: "구르에미르 · 업데이트 버전.", de: "Gur-e-Amir · Aktualisierte Version.", fr: "Gour-e Amir · Version mise à jour.", ja: "グル・アミール · 更新版。", tr: "Gur-e Amir · Güncel sürüm.", ar: "غور أمير · نسخة محدّثة." }),
  // ── Реклама и статусы ────────────────────────────────────────────
  с("РЕКЛАМА", { en: "AD", uz: "REKLAMA", zh: "广告", ko: "광고", de: "ANZEIGE", fr: "PUB", ja: "広告", tr: "REKLAM", ar: "إعلان" }),
  с("Перейти", { en: "Open", uz: "Oʻtish", zh: "前往", ko: "이동", de: "Öffnen", fr: "Ouvrir", ja: "開く", tr: "Git", ar: "انتقال" }),
  с("Заказать", { en: "Order", uz: "Buyurtma", zh: "预订", ko: "예약", de: "Bestellen", fr: "Commander", ja: "予約", tr: "Sipariş", ar: "اطلب" }),
  с("Купить билет", { en: "Buy ticket", uz: "Chipta olish", zh: "购票", ko: "티켓 구매", de: "Ticket kaufen", fr: "Acheter un billet", ja: "チケット購入", tr: "Bilet al", ar: "شراء تذكرة" }),
  с("Смотреть меню", { en: "View menu", uz: "Menyuni koʻrish", zh: "查看菜单", ko: "메뉴 보기", de: "Menü ansehen", fr: "Voir le menu", ja: "メニューを見る", tr: "Menüyü gör", ar: "عرض القائمة" }),
  с("Не посещено", { en: "Not visited", uz: "Tashrif buyurilmagan", zh: "未到访", ko: "미방문", de: "Nicht besucht", fr: "Non visité", ja: "未訪問", tr: "Ziyaret edilmedi", ar: "لم تُزَر" }),
  // ── Описания мест ────────────────────────────────────────────────
  с("Сердце древнего Самарканда — три великолепных медресе, украшенных лучшей мозаичной плиткой в мире. Объект Всемирного наследия ЮНЕСКО.", { en: "The heart of ancient Samarkand — three magnificent madrasahs clad in the world's finest mosaic tilework. A UNESCO World Heritage Site.", uz: "Qadimgi Samarqandning yuragi — dunyodagi eng nafis mozaika koshinlari bilan bezatilgan uchta ulugʻvor madrasa. YuNESKO Jahon merosi obyekti.", zh: "古城撒马尔罕的心脏——三座宏伟的经学院，饰以世界顶级的马赛克瓷砖。联合国教科文组织世界遗产。", ko: "고대 사마르칸트의 심장 — 세계 최고의 모자이크 타일로 장식된 세 개의 웅장한 마드라사. 유네스코 세계유산.", de: "Das Herz des alten Samarkand — drei prächtige Medresen mit den schönsten Mosaikfliesen der Welt. UNESCO-Weltkulturerbe.", fr: "Le cœur de l'antique Samarcande — trois madrasas majestueuses ornées des plus belles mosaïques au monde. Site du patrimoine mondial de l'UNESCO.", ja: "古都サマルカンドの中心——世界屈指のモザイクタイルで飾られた壮麗な三つのマドラサ。ユネスコ世界遺産。", tr: "Kadim Semerkant'ın kalbi — dünyanın en güzel mozaik çinileriyle bezeli üç görkemli medrese. UNESCO Dünya Mirası.", ar: "قلب سمرقند القديمة — ثلاث مدارس فخمة مكسوّة بأجمل فسيفساء في العالم. موقع تراث عالمي لليونسكو." }),
  с("Аллея мавзолеев — священный некрополь с куполами бирюзовых плиток, охватывающий семь веков исламского искусства.", { en: "An avenue of mausoleums — a sacred necropolis of turquoise-tiled domes spanning seven centuries of Islamic art.", uz: "Maqbaralar xiyoboni — yetti asrlik islom sanʼatini qamrab olgan, feruza koshinli gumbazlarga ega muqaddas nekropol.", zh: "陵墓大道——一座绿松石穹顶的圣陵，跨越七个世纪的伊斯兰艺术。", ko: "영묘의 거리 — 청록빛 타일 돔이 늘어선 성스러운 네크로폴리스, 이슬람 예술 7세기를 아우른다.", de: "Eine Allee der Mausoleen — eine heilige Nekropole mit türkisfarbenen Kuppeln, sieben Jahrhunderte islamischer Kunst.", fr: "Une allée de mausolées — une nécropole sacrée aux coupoles turquoise, sept siècles d'art islamique.", ja: "霊廟の並木道——七世紀にわたるイスラム美術を宿す、ターコイズタイルの聖なるネクロポリス。", tr: "Türbeler yolu — turkuaz çinili kubbeleriyle yedi yüzyıllık İslam sanatını barındıran kutsal nekropol.", ar: "جادة الأضرحة — مقبرة مقدّسة بقباب من الخزف الفيروزي تمتد عبر سبعة قرون من الفن الإسلامي." }),
  с("Гигантская крепость, служившая резиденцией эмиров Бухары на протяжении 14 веков.", { en: "A colossal fortress that served as the residence of Bukhara's emirs for fourteen centuries.", uz: "Oʻn toʻrt asr davomida Buxoro amirlariga qarorgoh boʻlib xizmat qilgan ulkan qalʼa.", zh: "一座巨型城堡，十四个世纪以来一直是布哈拉埃米尔的居所。", ko: "14세기 동안 부하라 에미르의 거처였던 거대한 요새.", de: "Eine gewaltige Festung, die vierzehn Jahrhunderte lang Residenz der Emire von Buchara war.", fr: "Une forteresse colossale, résidence des émirs de Boukhara pendant quatorze siècles.", ja: "14世紀にわたりブハラの首長の居城であった巨大な要塞。", tr: "On dört yüzyıl boyunca Buhara emirlerinin ikametgâhı olmuş dev bir kale.", ar: "قلعة هائلة كانت مقرّاً لأمراء بخارى طوال أربعة عشر قرناً." }),
  с("Внутренний обнесённый стеной город Хивы — живой музей, застывший во времени. Объект Всемирного наследия ЮНЕСКО.", { en: "Khiva's walled inner city — a living museum frozen in time. A UNESCO World Heritage Site.", uz: "Xivaning devor bilan oʻralgan ichki shahri — vaqt ichida qotib qolgan tirik muzey. YuNESKO Jahon merosi obyekti.", zh: "希瓦的内城——一座凝固于时光中的活博物馆。联合国教科文组织世界遗产。", ko: "성벽으로 둘러싸인 히바의 내성 — 시간이 멈춘 살아 있는 박물관. 유네스코 세계유산.", de: "Chiwas ummauerte Innenstadt — ein lebendiges Museum, in der Zeit erstarrt. UNESCO-Weltkulturerbe.", fr: "La ville intérieure fortifiée de Khiva — un musée vivant figé dans le temps. Site du patrimoine mondial de l'UNESCO.", ja: "城壁に囲まれたヒヴァの内城——時が止まった生きた博物館。ユネスコ世界遺産。", tr: "Hive'nin surlarla çevrili iç şehri — zamanda donmuş yaşayan bir müze. UNESCO Dünya Mirası.", ar: "مدينة خيوة الداخلية المسوّرة — متحف حيّ توقّف فيه الزمن. موقع تراث عالمي لليونسكو." }),
  с("«Башня смерти» — 800-летний минарет, который даже Чингисхан отказался разрушить.", { en: "The 'Tower of Death' — an 800-year-old minaret that even Genghis Khan refused to destroy.", uz: "«Oʻlim minorasi» — hatto Chingizxon ham buzishdan bosh tortgan 800 yillik minora.", zh: "“死亡之塔”——一座有800年历史的宣礼塔，连成吉思汗也不忍摧毁。", ko: "'죽음의 탑' — 칭기즈칸조차 파괴하기를 거부한 800년 된 미너렛.", de: "Der „Turm des Todes“ — ein 800 Jahre altes Minarett, das selbst Dschingis Khan verschonte.", fr: "La « tour de la mort » — un minaret vieux de 800 ans que même Gengis Khan refusa de détruire.", ja: "「死の塔」——チンギス・ハンさえ破壊を拒んだ800年前のミナレット。", tr: "'Ölüm Kulesi' — Cengiz Han'ın bile yıkmaya kıyamadığı 800 yıllık minare.", ar: "«برج الموت» — مئذنة عمرها 800 عام رفض حتى جنكيز خان هدمها." }),
  с("Мавзолей Тамерлана — шедевр тимуридской архитектуры с бирюзовым куполом высотой 34 метра.", { en: "Tamerlane's mausoleum — a masterpiece of Timurid architecture crowned by a 34-metre turquoise dome.", uz: "Amir Temur maqbarasi — 34 metrlik feruza gumbazli temuriylar meʼmorchiligi durdonasi.", zh: "帖木儿的陵墓——帖木儿王朝建筑的杰作，绿松石穹顶高达34米。", ko: "티무르의 영묘 — 34미터 청록빛 돔을 얹은 티무르 건축의 걸작.", de: "Timurs Mausoleum — ein Meisterwerk timuridischer Baukunst mit 34 Meter hoher türkisfarbener Kuppel.", fr: "Le mausolée de Tamerlan — chef-d'œuvre de l'architecture timouride coiffé d'une coupole turquoise de 34 mètres.", ja: "ティムールの霊廟——高さ34メートルのターコイズ・ドームを戴くティムール建築の傑作。", tr: "Timur'un türbesi — 34 metrelik turkuaz kubbesiyle Timur mimarisinin şaheseri.", ar: "ضريح تيمورلنك — تحفة العمارة التيمورية بقبّته الفيروزية التي يبلغ ارتفاعها 34 متراً." }),
  с("Живописное горное озеро в 80 км от Ташкента — идеально для пляжного отдыха и активного туризма.", { en: "A scenic mountain lake 80 km from Tashkent — perfect for beach days and outdoor adventures.", uz: "Toshkentdan 80 km uzoqlikdagi goʻzal togʻ koʻli — plyaj dam olishi va faol turizm uchun ideal.", zh: "距塔什干80公里的秀丽高山湖泊——海滩休闲与户外运动的理想之地。", ko: "타슈켄트에서 80km 떨어진 아름다운 산정 호수 — 해변 휴식과 액티비티에 최적.", de: "Ein malerischer Bergsee 80 km von Taschkent — ideal für Badetage und Aktivurlaub.", fr: "Un lac de montagne pittoresque à 80 km de Tachkent — idéal pour la plage et les activités de plein air.", ja: "タシケントから80kmの風光明媚な山上湖——ビーチ休暇とアウトドアに最適。", tr: "Taşkent'e 80 km uzaklıkta manzaralı bir dağ gölü — plaj tatili ve doğa sporları için ideal.", ar: "بحيرة جبلية خلّابة على بُعد 80 كم من طشقند — مثالية للاستجمام على الشاطئ والأنشطة." }),
  с("Главная площадь Ташкента — символ независимости Узбекистана, обрамлённый парками и фонтанами.", { en: "Tashkent's main square — a symbol of Uzbekistan's independence, framed by parks and fountains.", uz: "Toshkentning bosh maydoni — bogʻlar va favvoralar bilan oʻralgan, Oʻzbekiston mustaqilligi ramzi.", zh: "塔什干的中央广场——乌兹别克斯坦独立的象征，环绕着公园和喷泉。", ko: "타슈켄트의 중심 광장 — 공원과 분수로 둘러싸인 우즈베키스탄 독립의 상징.", de: "Taschkents Hauptplatz — Symbol der Unabhängigkeit Usbekistans, umgeben von Parks und Brunnen.", fr: "La place principale de Tachkent — symbole de l'indépendance de l'Ouzbékistan, bordée de parcs et de fontaines.", ja: "タシケントの中央広場——公園と噴水に囲まれた、ウズベキスタン独立の象徴。", tr: "Taşkent'in ana meydanı — parklar ve fıskiyelerle çevrili, Özbekistan bağımsızlığının simgesi.", ar: "الساحة الرئيسية في طشقند — رمز استقلال أوزبكستان، تحيط بها الحدائق والنوافير." }),
  с("Грандиозная соборная мечеть Тамерлана, построенная в 1399–1404 гг. Когда-то крупнейшая мечеть в исламском мире.", { en: "Tamerlane's grand congregational mosque, built in 1399–1404 — once the largest mosque in the Islamic world.", uz: "1399–1404 yillarda qurilgan Amir Temurning ulkan jome masjidi — bir vaqtlar islom olamidagi eng katta masjid.", zh: "帖木儿的宏伟聚礼清真寺，建于1399至1404年，曾是伊斯兰世界最大的清真寺。", ko: "1399~1404년에 세워진 티무르의 웅장한 금요 모스크 — 한때 이슬람 세계 최대 규모였다.", de: "Timurs gewaltige Freitagsmoschee von 1399–1404 — einst die größte Moschee der islamischen Welt.", fr: "La grande mosquée du vendredi de Tamerlan, bâtie en 1399–1404 — jadis la plus vaste du monde islamique.", ja: "1399〜1404年に建てられたティムールの壮大な金曜モスク——かつてイスラム世界最大を誇った。", tr: "1399–1404 yıllarında yapılan Timur'un görkemli ulu camisi — bir zamanlar İslam dünyasının en büyüğü.", ar: "جامع تيمورلنك الكبير الذي بُني بين 1399 و1404 — كان يوماً أكبر مسجد في العالم الإسلامي." }),
  с("Астрономическая обсерватория XV в. — Улугбек составил здесь звёздный каталог, опередив Европу на 150 лет.", { en: "A 15th-century observatory where Ulugbek compiled a star catalogue 150 years ahead of Europe.", uz: "XV asr astronomik rasadxonasi — Ulugʻbek bu yerda Yevropadan 150 yil oldin yulduzlar katalogini tuzgan.", zh: "15世纪的天文台——乌鲁伯格在此编制星表，领先欧洲150年。", ko: "15세기 천문대 — 울루그베크가 유럽보다 150년 앞서 별 목록을 작성한 곳.", de: "Eine Sternwarte des 15. Jahrhunderts — hier erstellte Ulugbek einen Sternkatalog, 150 Jahre vor Europa.", fr: "Un observatoire du XVe siècle où Ulugh Beg dressa un catalogue d'étoiles, 150 ans avant l'Europe.", ja: "15世紀の天文台——ウルグ・ベクがヨーロッパに150年先んじて星表を編んだ場所。", tr: "15. yüzyıldan bir rasathane — Uluğ Bey burada Avrupa'dan 150 yıl önce yıldız kataloğu hazırladı.", ar: "مرصد فلكي من القرن الخامس عشر — وضع فيه أولوغ بيك فهرساً للنجوم سبق أوروبا بـ150 عاماً." }),
  с("Живописный пруд в центре Бухары, окружённый медресе и чайханами — любимое место горожан с XVI в.", { en: "A picturesque pool in central Bukhara ringed by madrasahs and teahouses — a local favourite since the 16th century.", uz: "Buxoro markazidagi madrasa va choyxonalar bilan oʻralgan goʻzal hovuz — XVI asrdan beri shaharliklarning sevimli joyi.", zh: "布哈拉市中心的秀美水池，四周环绕经学院和茶馆——自16世纪起深受市民喜爱。", ko: "마드라사와 찻집으로 둘러싸인 부하라 중심의 아름다운 연못 — 16세기부터 시민들의 사랑을 받아온 곳.", de: "Ein malerischer Teich im Herzen Bucharas, umgeben von Medresen und Teehäusern — seit dem 16. Jahrhundert beliebt.", fr: "Un bassin pittoresque au cœur de Boukhara, entouré de madrasas et de maisons de thé — apprécié depuis le XVIe siècle.", ja: "マドラサと茶館に囲まれたブハラ中心の趣ある池——16世紀以来、市民に愛される場所。", tr: "Medreseler ve çayhanelerle çevrili, Buhara'nın kalbindeki manzaralı havuz — 16. yüzyıldan beri gözde.", ar: "بركة خلّابة في قلب بخارى تحيط بها المدارس والمقاهي — مقصد محبوب منذ القرن السادس عشر." }),
  с("Жемчужина центральноазиатской архитектуры IX–X вв. — один из старейших сохранившихся исламских мавзолеев.", { en: "A jewel of 9th–10th-century Central Asian architecture — one of the oldest surviving Islamic mausoleums.", uz: "IX–X asr Markaziy Osiyo meʼmorchiligining gavhari — saqlanib qolgan eng qadimgi islom maqbaralaridan biri.", zh: "9至10世纪中亚建筑的瑰宝——现存最古老的伊斯兰陵墓之一。", ko: "9~10세기 중앙아시아 건축의 보석 — 현존하는 가장 오래된 이슬람 영묘 중 하나.", de: "Ein Juwel zentralasiatischer Baukunst des 9.–10. Jahrhunderts — eines der ältesten erhaltenen islamischen Mausoleen.", fr: "Un joyau de l'architecture d'Asie centrale des IXe–Xe siècles — l'un des plus anciens mausolées islamiques conservés.", ja: "9〜10世紀の中央アジア建築の至宝——現存する最古のイスラム霊廟のひとつ。", tr: "9–10. yüzyıl Orta Asya mimarisinin incisi — günümüze ulaşan en eski İslam türbelerinden biri.", ar: "درّة العمارة في آسيا الوسطى من القرنين التاسع والعاشر — من أقدم الأضرحة الإسلامية الباقية." }),
  с("Самый высокий минарет Хивы (57 м) и медресе при нём — последний крупный памятник хивинского ханства, XIX в.", { en: "Khiva's tallest minaret (57 m) and its madrasah — the last great monument of the Khivan Khanate, 19th century.", uz: "Xivaning eng baland minorasi (57 m) va uning madrasasi — Xiva xonligining soʻnggi yirik yodgorligi, XIX asr.", zh: "希瓦最高的宣礼塔（57米）及附属经学院——希瓦汗国最后的宏伟遗迹，建于19世纪。", ko: "히바에서 가장 높은 미너렛(57m)과 부속 마드라사 — 19세기 히바 칸국의 마지막 대건축.", de: "Chiwas höchstes Minarett (57 m) samt Medrese — das letzte große Bauwerk des Khanats Chiwa, 19. Jahrhundert.", fr: "Le plus haut minaret de Khiva (57 m) et sa madrasa — dernier grand monument du khanat de Khiva, XIXe siècle.", ja: "ヒヴァ最高のミナレット（57m）と付属マドラサ——ヒヴァ・ハン国最後の大建築、19世紀。", tr: "Hive'nin en yüksek minaresi (57 m) ve medresesi — Hive Hanlığı'nın son büyük eseri, 19. yüzyıl.", ar: "أعلى مئذنة في خيوة (57 م) ومدرستها — آخر معالم خانية خيوة الكبرى، القرن التاسع عشر." }),
  с("Духовный центр Ташкента, где хранится один из старейших Коранов в мире — рукопись Усмана VII в.", { en: "Tashkent's spiritual heart, home to one of the world's oldest Qurans — the 7th-century Uthman manuscript.", uz: "Toshkentning maʼnaviy markazi — bu yerda dunyodagi eng qadimgi Qurʼonlardan biri, VII asr Usmon mushafi saqlanadi.", zh: "塔什干的精神中心，珍藏着世界上最古老的《古兰经》之一——7世纪的奥斯曼手抄本。", ko: "타슈켄트의 정신적 중심 — 세계에서 가장 오래된 쿠란 중 하나인 7세기 우스만 필사본을 소장.", de: "Taschkents spirituelles Zentrum, Heimat eines der ältesten Korane der Welt — der Uthman-Handschrift aus dem 7. Jahrhundert.", fr: "Le cœur spirituel de Tachkent, abritant l'un des plus anciens Corans au monde — le manuscrit d'Othman, VIIe siècle.", ja: "タシケントの精神的中心——世界最古級のクルアーン、7世紀のウスマーン写本を収蔵。", tr: "Taşkent'in manevi merkezi — dünyanın en eski Kur'an'larından biri olan 7. yüzyıl Osman mushafına ev sahipliği yapar.", ar: "القلب الروحي لطشقند، حيث يُحفظ أحد أقدم المصاحف في العالم — مصحف عثمان من القرن السابع." }),
  с("Старейший рынок Центральной Азии под синим куполом — специи, шёлк, фрукты, керамика и пряности со всего Шёлкового пути.", { en: "Central Asia's oldest market under a great blue dome — spices, silk, fruit, ceramics and aromas from across the Silk Road.", uz: "Koʻk gumbaz ostidagi Markaziy Osiyoning eng qadimgi bozori — Ipak yoʻli boʻylab ziravorlar, ipak, meva va sopol buyumlar.", zh: "蓝色穹顶下中亚最古老的市场——汇集丝绸之路沿线的香料、丝绸、水果与陶器。", ko: "푸른 돔 아래 중앙아시아에서 가장 오래된 시장 — 실크로드 곳곳의 향신료·비단·과일·도자기.", de: "Zentralasiens ältester Markt unter blauer Kuppel — Gewürze, Seide, Obst und Keramik von der ganzen Seidenstraße.", fr: "Le plus ancien marché d'Asie centrale sous une grande coupole bleue — épices, soie, fruits et céramiques de toute la Route de la soie.", ja: "青いドームの下に広がる中央アジア最古の市場——シルクロード各地の香辛料・絹・果物・陶器。", tr: "Mavi kubbenin altında Orta Asya'nın en eski çarşısı — İpek Yolu boyunca baharat, ipek, meyve ve seramik.", ar: "أقدم أسواق آسيا الوسطى تحت قبّة زرقاء — توابل وحرير وفواكه وخزف من طول طريق الحرير." }),
  с("Современная белоснежная мечеть (2014 г.) у набережной Боз-Су — жемчужина новой архитектуры Ташкента.", { en: "A gleaming white modern mosque (2014) on the Boz-Su embankment — a gem of Tashkent's new architecture.", uz: "Boʻzsuv qirgʻogʻidagi zamonaviy oppoq masjid (2014) — Toshkentning yangi meʼmorchiligi gavhari.", zh: "博兹苏河畔的现代洁白清真寺（2014年）——塔什干新建筑的明珠。", ko: "보즈수 강변의 새하얀 현대식 모스크(2014년) — 타슈켄트 신건축의 보석.", de: "Eine strahlend weiße moderne Moschee (2014) am Boz-Su-Ufer — ein Juwel der neuen Architektur Taschkents.", fr: "Une mosquée moderne d'un blanc éclatant (2014) sur les quais de la Boz-Sou — joyau de la nouvelle architecture de Tachkent.", ja: "ボズス川沿いの真っ白なモダンモスク（2014年）——タシケント新建築の逸品。", tr: "Boz-Su kıyısındaki bembeyaz modern cami (2014) — Taşkent'in yeni mimarisinin incisi.", ar: "مسجد حديث ناصع البياض (2014) على ضفة بوز-سو — درّة العمارة الجديدة في طشقند." }),
  с("Античная крепость I в. до н.э. в пустыне Кызылкум — один из самых драматичных силуэтов древнего Хорезма.", { en: "A 1st-century-BC desert fortress in the Kyzylkum — one of ancient Khorezm's most dramatic silhouettes.", uz: "Qizilqum sahrosidagi mil. avv. I asr qalʼasi — qadimgi Xorazmning eng taʼsirli manzaralaridan biri.", zh: "克孜勒库姆沙漠中公元前1世纪的古堡——古花剌子模最震撼的剪影之一。", ko: "키질쿰 사막에 선 기원전 1세기 요새 — 고대 호레즘의 가장 극적인 실루엣 중 하나.", de: "Eine Wüstenfestung aus dem 1. Jahrhundert v. Chr. in der Kysylkum — eine der eindrucksvollsten Silhouetten des alten Choresm.", fr: "Une forteresse du Ier siècle av. J.-C. dans le désert du Kyzylkoum — l'une des silhouettes les plus saisissantes de l'antique Khorezm.", ja: "クズルクム砂漠に立つ紀元前1世紀の城塞——古代ホラズム屈指の劇的なシルエット。", tr: "Kızılkum Çölü'nde MÖ 1. yüzyıldan bir kale — kadim Harezm'in en etkileyici silüetlerinden biri.", ar: "قلعة صحراوية من القرن الأول قبل الميلاد في صحراء قيزيلكوم — من أبهى معالم خوارزم القديمة." }),
  с("Дом-музей великого поэта Алишера Навои с редкими рукописями и предметами быта эпохи Тимуридов.", { en: "The house-museum of the great poet Alisher Navoi, with rare manuscripts and everyday objects from the Timurid era.", uz: "Buyuk shoir Alisher Navoiy uy-muzeyi — noyob qoʻlyozmalar va temuriylar davri buyumlari bilan.", zh: "伟大诗人阿利舍尔·纳沃伊的故居博物馆，藏有帖木儿时代的珍稀手稿与生活器物。", ko: "위대한 시인 알리셰르 나보이의 생가 박물관 — 티무르 시대의 희귀 필사본과 생활용품.", de: "Das Hausmuseum des großen Dichters Alischer Navoi mit seltenen Handschriften und Alltagsobjekten der Timuridenzeit.", fr: "La maison-musée du grand poète Alicher Navoï, aux manuscrits rares et objets du quotidien de l'époque timouride.", ja: "偉大な詩人アリシェル・ナヴォイの家博物館——ティムール朝時代の稀少な写本と生活用品を展示。", tr: "Büyük şair Ali Şir Nevai'nin ev-müzesi — nadir el yazmaları ve Timur dönemi eşyalarıyla.", ar: "بيت-متحف الشاعر الكبير علي شير نوائي، يضمّ مخطوطات نادرة وأدوات من العصر التيموري." }),
  с("Горный курорт в 80 км от Ташкента — треккинг, лыжи зимой, водопады и панорамы на Тянь-Шань.", { en: "A mountain resort 80 km from Tashkent — trekking, winter skiing, waterfalls and Tian Shan panoramas.", uz: "Toshkentdan 80 km uzoqlikdagi togʻ kurorti — trekking, qishda changʻi, sharsharalar va Tyan-Shan manzaralari.", zh: "距塔什干80公里的山地度假胜地——徒步、冬季滑雪、瀑布与天山全景。", ko: "타슈켄트에서 80km 떨어진 산악 리조트 — 트레킹, 겨울 스키, 폭포, 톈산 파노라마.", de: "Ein Bergresort 80 km von Taschkent — Trekking, Skifahren im Winter, Wasserfälle und Panoramen des Tienschan.", fr: "Une station de montagne à 80 km de Tachkent — randonnée, ski en hiver, cascades et panoramas du Tian Shan.", ja: "タシケントから80kmの山岳リゾート——トレッキング、冬のスキー、滝、天山山脈の眺望。", tr: "Taşkent'e 80 km uzaklıkta bir dağ merkezi — trekking, kışın kayak, şelaleler ve Tanrı Dağları manzarası.", ar: "منتجع جبلي على بُعد 80 كم من طشقند — تسلّق وتزلّج شتوي وشلالات وإطلالات على تيان شان." }),
  с("Старейший рынок Самарканда у подножия Шахи-Зинды — здесь торгуют нонами, специями и узбекскими сладостями с древних времён.", { en: "Samarkand's oldest bazaar at the foot of Shah-i-Zinda — non bread, spices and Uzbek sweets sold here since ancient times.", uz: "Shohi Zinda etagidagi Samarqandning eng qadimgi bozori — bu yerda qadimdan non, ziravor va oʻzbek shirinliklari sotiladi.", zh: "夏伊辛达脚下撒马尔罕最古老的集市——自古出售馕、香料与乌兹别克甜点。", ko: "샤히진다 기슭에 자리한 사마르칸트에서 가장 오래된 시장 — 예로부터 논 빵·향신료·우즈베크 과자를 판다.", de: "Samarkands ältester Basar am Fuße von Schah-i-Sinda — hier gibt es seit alters Non-Brot, Gewürze und usbekische Süßigkeiten.", fr: "Le plus ancien bazar de Samarcande au pied de Chah-e-Zindeh — pain non, épices et douceurs ouzbèkes depuis l'Antiquité.", ja: "シャーヒズィンダの麓に広がるサマルカンド最古のバザール——古来よりノン、香辛料、ウズベクの菓子を商う。", tr: "Şah-ı Zinde'nin eteğinde Semerkant'ın en eski pazarı — kadim zamanlardan beri non ekmeği, baharat ve Özbek tatlıları.", ar: "أقدم أسواق سمرقند عند سفح شاهي زندة — يُباع فيه خبز النون والتوابل والحلويات الأوزبكية منذ القِدم." }),
  // ── Описания отелей ──────────────────────────────────────────────
  с("Роскошный отель с видом на Регистан. Бассейн на крыше, узбекские завтраки и персонализированный консьерж-сервис.", { en: "A luxury hotel overlooking the Registan. Rooftop pool, Uzbek breakfasts and a personalised concierge service.", uz: "Registonga qaragan hashamatli mehmonxona. Tomdagi hovuz, oʻzbekcha nonushta va shaxsiy konserj xizmati.", zh: "俯瞰雷吉斯坦的豪华酒店。屋顶泳池、乌兹别克早餐及个性化礼宾服务。", ko: "레기스탄이 내려다보이는 럭셔리 호텔. 루프톱 수영장, 우즈베크식 조식, 맞춤 컨시어지 서비스.", de: "Ein Luxushotel mit Blick auf den Registan. Dachpool, usbekisches Frühstück und persönlicher Concierge-Service.", fr: "Un hôtel de luxe surplombant le Reguistan. Piscine sur le toit, petits-déjeuners ouzbeks et conciergerie personnalisée.", ja: "レギスタンを望むラグジュアリーホテル。屋上プール、ウズベク式朝食、専属コンシェルジュ。", tr: "Registan manzaralı lüks otel. Çatı havuzu, Özbek kahvaltıları ve kişiye özel konsiyerj hizmeti.", ar: "فندق فاخر يطلّ على ريغستان. مسبح على السطح، وإفطار أوزبكي، وخدمة كونسيرج شخصية." }),
  с("Исторический бутик-отель в сердце старого города Бухары. Традиционная архитектура в сочетании с современным комфортом.", { en: "A historic boutique hotel in the heart of old Bukhara. Traditional architecture paired with modern comfort.", uz: "Buxoro eski shahri markazidagi tarixiy butik-mehmonxona. Anʼanaviy meʼmorchilik zamonaviy qulaylik bilan uygʻunlashgan.", zh: "位于布哈拉老城中心的历史精品酒店。传统建筑与现代舒适完美结合。", ko: "부하라 구시가지 중심의 역사적 부티크 호텔. 전통 건축과 현대적 편안함의 조화.", de: "Ein historisches Boutique-Hotel im Herzen der Altstadt von Buchara. Traditionelle Architektur trifft modernen Komfort.", fr: "Un hôtel de charme historique au cœur de la vieille ville de Boukhara. Architecture traditionnelle et confort moderne.", ja: "ブハラ旧市街の中心にある歴史あるブティックホテル。伝統建築とモダンな快適さの融合。", tr: "Buhara eski şehrinin kalbinde tarihi butik otel. Geleneksel mimari, modern konforla buluşuyor.", ar: "فندق بوتيك تاريخي في قلب مدينة بخارى القديمة. عمارة تقليدية تمتزج براحة عصرية." }),
  с("Единственный отель внутри крепостных стен Ичан-Калы. Просыпайтесь в окружении 2500-летней истории.", { en: "The only hotel within the walls of Ichan-Kala. Wake up surrounded by 2,500 years of history.", uz: "Ichan Qalʼa devorlari ichidagi yagona mehmonxona. 2500 yillik tarix qurshovida uygʻoning.", zh: "伊禅卡拉城墙内唯一的酒店。在2500年的历史环抱中醒来。", ko: "이찬칼라 성벽 안에 있는 유일한 호텔. 2,500년 역사에 둘러싸여 아침을 맞이하세요.", de: "Das einzige Hotel innerhalb der Mauern von Itschan Qalʼa. Erwachen Sie umgeben von 2.500 Jahren Geschichte.", fr: "Le seul hôtel à l'intérieur des remparts d'Itchan Kala. Réveillez-vous entouré de 2 500 ans d'histoire.", ja: "イチャン・カラの城壁内で唯一のホテル。2500年の歴史に包まれて目覚める。", tr: "İçan Kale surlarının içindeki tek otel. 2.500 yıllık tarihin ortasında uyanın.", ar: "الفندق الوحيد داخل أسوار إيتشان قلعة. استيقظ محاطاً بتاريخ عمره 2500 عام." }),
  с("5-звёздочный отель в деловом центре Ташкента с бассейном, фитнесом и панорамным рестораном.", { en: "A five-star hotel in Tashkent's business district with a pool, fitness centre and panoramic restaurant.", uz: "Toshkent biznes markazidagi 5 yulduzli mehmonxona — hovuz, fitnes va panoramali restoran bilan.", zh: "位于塔什干商务区的五星级酒店，设有泳池、健身房和全景餐厅。", ko: "타슈켄트 비즈니스 지구의 5성급 호텔 — 수영장, 피트니스, 파노라마 레스토랑.", de: "Ein Fünf-Sterne-Hotel im Geschäftsviertel Taschkents mit Pool, Fitness und Panoramarestaurant.", fr: "Un hôtel cinq étoiles dans le quartier d'affaires de Tachkent, avec piscine, fitness et restaurant panoramique.", ja: "タシケントのビジネス街に建つ5つ星ホテル。プール、フィットネス、パノラマレストランを備える。", tr: "Taşkent iş merkezinde havuzu, fitness'ı ve panoramik restoranı olan 5 yıldızlı otel.", ar: "فندق خمس نجوم في حيّ الأعمال بطشقند، مع مسبح وصالة رياضية ومطعم بانورامي." }),
  с("Удобный отель в 5 минутах ходьбы от Регистана — идеальное соотношение цены и качества.", { en: "A convenient hotel a five-minute walk from the Registan — excellent value for money.", uz: "Registonga 5 daqiqa piyoda masofadagi qulay mehmonxona — narx va sifat mutanosibligi ideal.", zh: "距雷吉斯坦步行5分钟的便捷酒店——性价比极佳。", ko: "레기스탄에서 도보 5분 거리의 편리한 호텔 — 가성비가 뛰어나다.", de: "Ein bequemes Hotel fünf Gehminuten vom Registan — hervorragendes Preis-Leistungs-Verhältnis.", fr: "Un hôtel pratique à cinq minutes à pied du Reguistan — un excellent rapport qualité-prix.", ja: "レギスタンから徒歩5分の便利なホテル——コストパフォーマンスに優れる。", tr: "Registan'a 5 dakika yürüme mesafesinde konforlu bir otel — mükemmel fiyat-performans.", ar: "فندق مريح على بُعد خمس دقائق سيراً من ريغستان — قيمة ممتازة مقابل السعر." }),
  с("Уютный бутик-отель с традиционным узбекским двориком и панорамной террасой.", { en: "A cosy boutique hotel with a traditional Uzbek courtyard and a panoramic terrace.", uz: "Anʼanaviy oʻzbek hovlisi va panoramali terrasali shinam butik-mehmonxona.", zh: "温馨的精品酒店，配有传统乌兹别克庭院和全景露台。", ko: "전통 우즈베크 안뜰과 파노라마 테라스를 갖춘 아늑한 부티크 호텔.", de: "Ein gemütliches Boutique-Hotel mit traditionellem usbekischem Innenhof und Panoramaterrasse.", fr: "Un hôtel de charme douillet avec cour ouzbèke traditionnelle et terrasse panoramique.", ja: "伝統的なウズベクの中庭とパノラマテラスを備えた居心地のよいブティックホテル。", tr: "Geleneksel Özbek avlusu ve panoramik terası olan şirin bir butik otel.", ar: "فندق بوتيك دافئ بفناء أوزبكي تقليدي وتراس بانورامي." }),
  с("Отель у стен Ичан-Калы с террасой и видом на минареты. Традиционный декор и современный сервис.", { en: "A hotel by the walls of Ichan-Kala with a terrace and minaret views. Traditional décor, modern service.", uz: "Ichan Qalʼa devorlari yonidagi mehmonxona — terrasa va minoralar manzarasi. Anʼanaviy bezak, zamonaviy xizmat.", zh: "毗邻伊禅卡拉城墙的酒店，设有露台并可眺望宣礼塔。传统装饰，现代服务。", ko: "이찬칼라 성벽 옆에 자리한 호텔 — 테라스와 미너렛 전망. 전통 장식과 현대적 서비스.", de: "Ein Hotel an den Mauern von Itschan Qalʼa mit Terrasse und Minarettblick. Traditionelles Dekor, moderner Service.", fr: "Un hôtel au pied des remparts d'Itchan Kala, avec terrasse et vue sur les minarets. Décor traditionnel, service moderne.", ja: "イチャン・カラの城壁沿いに建つホテル。テラスとミナレットの眺め。伝統的な内装とモダンなサービス。", tr: "İçan Kale surlarının yanında, teraslı ve minare manzaralı otel. Geleneksel dekor, modern hizmet.", ar: "فندق عند أسوار إيتشان قلعة بتراس وإطلالة على المآذن. ديكور تقليدي وخدمة عصرية." }),
  // ── Описания ресторанов ──────────────────────────────────────────
  с("Легендарное место — лучший плов в Узбекистане. Готовят с 7 утра в огромных казанах, к полудню всё разбирают.", { en: "A legendary spot serving Uzbekistan's best plov. Cooked from 7 a.m. in giant cauldrons and gone by noon.", uz: "Afsonaviy joy — Oʻzbekistondagi eng mazali osh. Ertalab 7 dan katta qozonlarda pishiriladi, tushga qadar tugaydi.", zh: "传奇之地，供应乌兹别克斯坦最好的抓饭。清晨7点起用大锅烹制，午前便告售罄。", ko: "우즈베키스탄 최고의 플로프를 내는 전설적인 곳. 오전 7시부터 큰 가마솥에 짓고 정오면 동난다.", de: "Ein legendärer Ort mit dem besten Plov Usbekistans. Ab 7 Uhr in riesigen Kesseln gekocht, mittags ausverkauft.", fr: "Une adresse légendaire servant le meilleur plov d'Ouzbékistan. Cuit dès 7 h dans d'immenses chaudrons, épuisé avant midi.", ja: "ウズベキスタン随一のプロフを出す伝説の店。朝7時から大鍋で炊き、正午には売り切れる。", tr: "Özbekistan'ın en iyi plovunu sunan efsanevi mekân. Sabah 7'den itibaren dev kazanlarda pişer, öğlene kalmaz.", ar: "مكان أسطوري يقدّم أفضل بلوف في أوزبكستان. يُطهى من السابعة صباحاً في قدور ضخمة وينفد قبل الظهر." }),
  с("Современная узбекская кухня фьюжн в центре Ташкента. Вино, шашлык, живая музыка по пятницам.", { en: "Modern Uzbek fusion cuisine in central Tashkent. Wine, shashlik and live music on Fridays.", uz: "Toshkent markazida zamonaviy oʻzbek fyujn oshxonasi. Vino, shashlik, juma kunlari jonli musiqa.", zh: "塔什干市中心的现代乌兹别克融合料理。美酒、烤肉，周五有现场音乐。", ko: "타슈켄트 도심의 현대적 우즈베크 퓨전 요리. 와인, 샤슬릭, 금요일 라이브 음악.", de: "Moderne usbekische Fusionsküche im Zentrum Taschkents. Wein, Schaschlik und freitags Livemusik.", fr: "Cuisine ouzbèke fusion moderne au centre de Tachkent. Vin, chachlik et musique live le vendredi.", ja: "タシケント中心部のモダンなウズベク・フュージョン料理。ワイン、シャシリク、金曜は生演奏。", tr: "Taşkent merkezinde modern Özbek füzyon mutfağı. Şarap, şaşlık ve cuma günleri canlı müzik.", ar: "مطبخ أوزبكي عصري مندمج في وسط طشقند. نبيذ وشواء وموسيقى حيّة أيام الجمعة." }),
  с("Старейшая чайхана Ташкента с 1958 года. Самса, лепёшки, нишалда и зелёный чай в атмосфере советского прошлого.", { en: "Tashkent's oldest teahouse since 1958. Samsa, flatbread, nishalda and green tea in a Soviet-era atmosphere.", uz: "1958 yildan beri Toshkentning eng qadimgi choyxonasi. Somsa, non, nishalda va koʻk choy — sovet davri ruhida.", zh: "塔什干最古老的茶馆，创立于1958年。萨姆萨、馕、尼沙尔达与绿茶，尽显苏联时代氛围。", ko: "1958년부터 이어진 타슈켄트에서 가장 오래된 찻집. 삼사·논빵·니샬다·녹차를 소비에트 시절 분위기에서.", de: "Taschkents ältestes Teehaus seit 1958. Samsa, Fladenbrot, Nischalda und grüner Tee in Sowjet-Atmosphäre.", fr: "La plus ancienne maison de thé de Tachkent depuis 1958. Samsa, galettes, nichalda et thé vert dans une ambiance soviétique.", ja: "1958年創業、タシケント最古の茶館。ソ連時代の趣の中でサムサ、ノン、ニシャルダ、緑茶を。", tr: "1958'den beri Taşkent'in en eski çayhanesi. Somsa, ekmek, nişalda ve yeşil çay — Sovyet dönemi havasında.", ar: "أقدم مقهى شاي في طشقند منذ 1958. سمسة وخبز ونيشالدا وشاي أخضر في أجواء الحقبة السوفييتية." }),
  с("Терраса с видом на Регистан — лучшее место для заката. Плов, лагман, долма и свежие узбекские лепёшки.", { en: "A terrace overlooking the Registan — the best spot for sunset. Plov, lagman, dolma and fresh Uzbek flatbread.", uz: "Registonga qaragan terrasa — quyosh botishini kuzatish uchun eng zoʻr joy. Osh, lagʻmon, dolma va yangi non.", zh: "俯瞰雷吉斯坦的露台——观赏日落的最佳去处。抓饭、拉条子、多尔玛与新鲜乌兹别克馕。", ko: "레기스탄이 보이는 테라스 — 일몰 감상 최고의 자리. 플로프·라그만·돌마와 갓 구운 논빵.", de: "Eine Terrasse mit Blick auf den Registan — der beste Platz für den Sonnenuntergang. Plov, Lagman, Dolma und frisches Non-Brot.", fr: "Une terrasse dominant le Reguistan — le meilleur endroit au coucher du soleil. Plov, laghman, dolma et pain non frais.", ja: "レギスタンを望むテラス——夕日鑑賞に最適。プロフ、ラグマン、ドルマ、焼きたてのノン。", tr: "Registan manzaralı teras — gün batımı için en iyi yer. Plov, lağman, dolma ve taze Özbek ekmeği.", ar: "تراس يطلّ على ريغستان — أفضل مكان لغروب الشمس. بلوف ولغمان ودولما وخبز أوزبكي طازج." }),
  с("Самаркандский плов — особенный: жёлтый рис, нут, айва и баранина. Здесь его готовят по старинному рецепту.", { en: "Samarkand plov is special — yellow rice, chickpeas, quince and lamb, cooked here to an age-old recipe.", uz: "Samarqand oshi oʻziga xos: sargʻish guruch, noʻxat, behi va qoʻy goʻshti. Bu yerda qadimiy retsept boʻyicha tayyorlanadi.", zh: "撒马尔罕抓饭别具一格：黄米、鹰嘴豆、木瓜与羊肉，此处遵循古法烹制。", ko: "사마르칸트 플로프는 특별하다 — 노란 쌀·병아리콩·모과·양고기를 옛 방식대로 짓는다.", de: "Samarkand-Plov ist besonders — gelber Reis, Kichererbsen, Quitte und Lamm, hier nach altem Rezept zubereitet.", fr: "Le plov de Samarcande est unique — riz jaune, pois chiches, coing et agneau, préparé ici selon une recette ancestrale.", ja: "サマルカンドのプロフは格別——黄色い米、ひよこ豆、マルメロ、羊肉を古来のレシピで炊く。", tr: "Semerkant plovu özeldir — sarı pirinç, nohut, ayva ve kuzu, burada asırlık tarifle pişer.", ar: "بلوف سمرقند مميّز — أرزّ أصفر وحمّص وسفرجل ولحم ضأن، يُطهى هنا بوصفة عريقة." }),
  с("Авторская кухня Шёлкового пути: специи, пряности и традиционные рецепты в современной интерпретации.", { en: "Signature Silk Road cuisine: spices, aromatics and traditional recipes reimagined for today.", uz: "Ipak yoʻli mualliflik oshxonasi: ziravorlar va anʼanaviy retseptlar zamonaviy talqinda.", zh: "丝绸之路创意料理：香料、调味与传统食谱的现代演绎。", ko: "실크로드 시그니처 요리: 향신료와 전통 레시피를 현대적으로 재해석.", de: "Signature-Küche der Seidenstraße: Gewürze, Aromen und traditionelle Rezepte modern interpretiert.", fr: "Cuisine signature de la Route de la soie : épices, aromates et recettes traditionnelles réinventées.", ja: "シルクロードのシグネチャー料理——香辛料と伝統レシピを現代的に再解釈。", tr: "İpek Yolu imza mutfağı: baharatlar ve geleneksel tarifler modern yorumla.", ar: "مطبخ طريق الحرير المميّز: توابل ووصفات تقليدية بلمسة عصرية." }),
  с("На берегу знаменитого пруда Ляби-Хауз. Узбекские блюда, чай с халвой и виды на медресе Надир-Диван-Беги.", { en: "On the shore of the famous Lyabi-Hauz pool. Uzbek dishes, tea with halva and views of the Nadir Divan-Begi madrasah.", uz: "Mashhur Labi Hovuz boʻyida. Oʻzbek taomlari, holva bilan choy va Nodir Devonbegi madrasasi manzarasi.", zh: "坐落于著名的拉比豪兹水池畔。乌兹别克美食、哈尔瓦配茶，可眺望纳迪尔·迪万·贝吉经学院。", ko: "유명한 라비하우즈 연못가에 위치. 우즈베크 요리, 할바를 곁들인 차, 나디르 디반베기 마드라사 전망.", de: "Am Ufer des berühmten Lyabi-Hauz-Teichs. Usbekische Gerichte, Tee mit Halva und Blick auf die Nadir-Diwan-Begi-Medrese.", fr: "Au bord du célèbre bassin Lyabi-Haouz. Plats ouzbeks, thé au halva et vue sur la madrasa Nadir Divan-Begi.", ja: "名高いラビハウズの池のほとり。ウズベク料理、ハルヴァ添えの茶、ナディール・ディヴァンベギ・マドラサの眺め。", tr: "Ünlü Lyabi-Havuz göletinin kıyısında. Özbek yemekleri, helvalı çay ve Nadir Divan-Begi medresesi manzarası.", ar: "على ضفة بركة لبّي حوض الشهيرة. أطباق أوزبكية وشاي مع الحلوى وإطلالة على مدرسة نادر ديوان بيغي." }),
  с("Уютный ресторан в историческом здании с открытым двориком. Шашлык из тандыра, манты и бухарская самса.", { en: "A cosy restaurant in a historic building with an open courtyard. Tandoor shashlik, manti and Bukhara samsa.", uz: "Ochiq hovlili tarixiy binodagi shinam restoran. Tandir shashligi, manti va buxorocha somsa.", zh: "坐落于历史建筑内、带露天庭院的温馨餐厅。坦都尔烤肉、蒸包与布哈拉萨姆萨。", ko: "열린 안뜰이 있는 역사적 건물 속 아늑한 레스토랑. 탄두르 샤슬릭·만티·부하라 삼사.", de: "Ein gemütliches Restaurant in einem historischen Gebäude mit offenem Hof. Tandoor-Schaschlik, Manti und Buchara-Samsa.", fr: "Un restaurant chaleureux dans un bâtiment historique avec cour ouverte. Chachlik au tandoor, manti et samsa de Boukhara.", ja: "中庭のある歴史的建物の中の居心地のよいレストラン。タンドール焼きシャシリク、マントゥ、ブハラ風サムサ。", tr: "Açık avlulu tarihi bir binada şirin restoran. Tandır şaşlığı, mantı ve Buhara somsası.", ar: "مطعم دافئ في مبنى تاريخي بفناء مفتوح. شواء التنّور والمانتي وسمسة بخارى." }),
  с("Народная чайхана прямо у Регистана — завтрак из самсы и чай за $2, как у местных.", { en: "A down-to-earth teahouse right by the Registan — a samsa breakfast and tea for $2, just like the locals.", uz: "Registon yonidagi oddiy choyxona — somsa nonushtasi va choy 2 dollarga, mahalliylar kabi.", zh: "紧邻雷吉斯坦的平民茶馆——2美元享用萨姆萨早餐配茶，像当地人一样。", ko: "레기스탄 바로 옆 서민 찻집 — 삼사 아침과 차 2달러, 현지인처럼.", de: "Ein bodenständiges Teehaus direkt am Registan — Samsa-Frühstück und Tee für 2 $, ganz wie die Einheimischen.", fr: "Une maison de thé populaire juste à côté du Reguistan — petit-déjeuner samsa et thé pour 2 $, comme les habitants.", ja: "レギスタンのすぐそばの庶民的な茶館——サムサの朝食と茶で2ドル、地元流に。", tr: "Tam Registan'ın yanında halk çayhanesi — 2 dolara somsa kahvaltısı ve çay, tıpkı yerliler gibi.", ar: "مقهى شاي شعبي بجوار ريغستان مباشرة — فطور سمسة وشاي بدولارين، كما يفعل الأهالي." }),
  с("Ресторан внутри Ичан-Калы. Хивинский плов, шурпа и долма в атмосфере средневекового города.", { en: "A restaurant inside Ichan-Kala. Khivan plov, shurpa and dolma in the atmosphere of a medieval city.", uz: "Ichan Qalʼa ichidagi restoran. Xiva oshi, shoʻrva va dolma — oʻrta asr shahri ruhida.", zh: "位于伊禅卡拉城内的餐厅。希瓦抓饭、舒尔帕汤与多尔玛，尽在中世纪古城的氛围中。", ko: "이찬칼라 안에 있는 레스토랑. 중세 도시의 분위기 속 히바 플로프·슈르파·돌마.", de: "Ein Restaurant innerhalb von Itschan Qalʼa. Chiwa-Plov, Schurpa und Dolma in der Atmosphäre einer mittelalterlichen Stadt.", fr: "Un restaurant à l'intérieur d'Itchan Kala. Plov de Khiva, chourpa et dolma dans l'ambiance d'une cité médiévale.", ja: "イチャン・カラ内のレストラン。中世都市の趣の中でヒヴァ風プロフ、シュルパ、ドルマを。", tr: "İçan Kale içinde bir restoran. Ortaçağ şehri havasında Hive plovu, şurpa ve dolma.", ar: "مطعم داخل إيتشان قلعة. بلوف خيوة والشوربة والدولما في أجواء مدينة من العصور الوسطى." }),
  с("Крышный ресторан с панорамой на минареты Хивы — идеально для ужина на закате.", { en: "A rooftop restaurant with panoramic views of Khiva's minarets — perfect for a sunset dinner.", uz: "Xiva minoralariga panorama ochiladigan tomdagi restoran — quyosh botishida kechki ovqat uchun ideal.", zh: "可俯瞰希瓦宣礼塔全景的屋顶餐厅——日落晚餐的理想之选。", ko: "히바 미너렛을 한눈에 담는 루프톱 레스토랑 — 일몰 디너에 안성맞춤.", de: "Ein Dachrestaurant mit Panoramablick auf Chiwas Minarette — ideal für ein Abendessen bei Sonnenuntergang.", fr: "Un restaurant sur le toit avec vue panoramique sur les minarets de Khiva — parfait pour un dîner au coucher du soleil.", ja: "ヒヴァのミナレットを一望する屋上レストラン——夕暮れのディナーに最適。", tr: "Hive minarelerinin panoramasına bakan çatı restoranı — gün batımı yemeği için ideal.", ar: "مطعم على السطح بإطلالة بانورامية على مآذن خيوة — مثالي لعشاء عند الغروب." }),
  с("Ферганский плов — самый жирный и ароматный в Узбекистане. Готовят только до обеда, заканчивается быстро.", { en: "Fergana plov — the richest and most fragrant in Uzbekistan. Cooked only until midday and gone fast.", uz: "Fargʻona oshi — Oʻzbekistondagi eng sermoy va xushboʻyi. Faqat tushgacha pishiriladi, tez tugaydi.", zh: "费尔干纳抓饭——乌兹别克斯坦最油润、最香的抓饭。只做到午前，很快售罄。", ko: "페르가나 플로프 — 우즈베키스탄에서 가장 기름지고 향이 진하다. 정오까지만 짓고 금세 동난다.", de: "Fergana-Plov — der gehaltvollste und aromatischste Usbekistans. Nur bis mittags gekocht und schnell weg.", fr: "Le plov de Ferghana — le plus riche et parfumé d'Ouzbékistan. Préparé seulement jusqu'à midi, il part vite.", ja: "フェルガナのプロフ——ウズベキスタンで最も濃厚で香り高い。昼までしか作らず、すぐ売り切れる。", tr: "Fergana plovu — Özbekistan'ın en yağlı ve en kokulusu. Yalnızca öğlene kadar pişer, çabuk biter.", ar: "بلوف فرغانة — الأدسم والأكثر عطراً في أوزبكستان. يُطهى حتى الظهر فقط وينفد سريعاً." }),
  с("Ресторан с садом и фонтанами — домашняя узбекская кухня: казан-кабоб, чучвара и свежие соки.", { en: "A restaurant with a garden and fountains — home-style Uzbek cooking: kazan-kabob, chuchvara and fresh juices.", uz: "Bogʻ va favvorali restoran — uy sharoitidagi oʻzbek taomlari: qozon-kabob, chuchvara va yangi sharbatlar.", zh: "带花园和喷泉的餐厅——地道乌兹别克家常菜：卡赞烤肉、馄饨与鲜榨果汁。", ko: "정원과 분수가 있는 레스토랑 — 가정식 우즈베크 요리: 카잔 카밥·추치바라·생과일주스.", de: "Ein Restaurant mit Garten und Brunnen — hausgemachte usbekische Küche: Kazan-Kabob, Tschutschwara und frische Säfte.", fr: "Un restaurant avec jardin et fontaines — cuisine ouzbèke maison : kazan-kabob, tchoutchvara et jus frais.", ja: "庭園と噴水のあるレストラン——家庭的なウズベク料理：カザン・カボブ、チュチュワラ、フレッシュジュース。", tr: "Bahçeli ve fıskiyeli restoran — ev usulü Özbek mutfağı: kazan kebabı, çuçvara ve taze meyve suları.", ar: "مطعم بحديقة ونوافير — مطبخ أوزبكي منزلي: كازان كباب وتشوتشفارا وعصائر طازجة." }),
  с("Лучший шашлык Самарканда — люля, баранина, перепел на углях. Живая узбекская музыка каждый вечер.", { en: "Samarkand's best grill — lyulya, lamb and quail over coals. Live Uzbek music every evening.", uz: "Samarqandning eng zoʻr shashligi — lula, qoʻy goʻshti, choʻrtan choʻgʻda. Har oqshom jonli oʻzbek musiqasi.", zh: "撒马尔罕最棒的烤肉——碳烤露露烤肠、羊肉与鹌鹑。每晚有乌兹别克现场音乐。", ko: "사마르칸트 최고의 그릴 — 숯불에 굽는 룰라·양고기·메추라기. 매일 저녁 우즈베크 라이브 음악.", de: "Samarkands bester Grill — Ljulja, Lamm und Wachtel über Kohlen. Jeden Abend usbekische Livemusik.", fr: "Le meilleur grill de Samarcande — lioulia, agneau et caille sur braises. Musique ouzbèke live chaque soir.", ja: "サマルカンド随一のグリル——炭火のリュリャ、羊肉、ウズラ。毎晩ウズベクの生演奏。", tr: "Semerkant'ın en iyi ızgarası — köz üstünde lüle, kuzu ve bıldırcın. Her akşam canlı Özbek müziği.", ar: "أفضل مشاوي سمرقند — لولا ولحم ضأن وسمّان على الجمر. موسيقى أوزبكية حيّة كل مساء." }),
  с("Классическая бухарская чайхана: лепёшки из тандыра, чай в пиалах и местная атмосфера.", { en: "A classic Bukhara teahouse: tandoor flatbread, tea in piyala bowls and a truly local atmosphere.", uz: "Klassik buxorocha choyxona: tandir noni, piyoladagi choy va mahalliy muhit.", zh: "经典的布哈拉茶馆：坦都尔烤馕、盏中清茶与地道的当地氛围。", ko: "고전적인 부하라 찻집: 탄두르 논빵, 피알라 잔에 담은 차, 현지 특유의 분위기.", de: "Ein klassisches Teehaus in Buchara: Tandoor-Fladenbrot, Tee in Pijala-Schalen und echte lokale Atmosphäre.", fr: "Une maison de thé classique de Boukhara : pain au tandoor, thé en bols piala et ambiance locale authentique.", ja: "ブハラの伝統的な茶館：タンドール焼きのノン、ピアラ碗の茶、地元らしい雰囲気。", tr: "Klasik bir Buhara çayhanesi: tandır ekmeği, piyalede çay ve yerel atmosfer.", ar: "مقهى شاي بخاري كلاسيكي: خبز التنّور والشاي في أقداح البيالة وأجواء محلّية أصيلة." }),
  // ── Удобства отелей ──────────────────────────────────────────────
  с("Бассейн", { en: "Pool", uz: "Basseyn", zh: "泳池", ko: "수영장", de: "Pool", fr: "Piscine", ja: "プール", tr: "Havuz", ar: "مسبح" }),
  с("Ресторан", { en: "Restaurant", uz: "Restoran", zh: "餐厅", ko: "레스토랑", de: "Restaurant", fr: "Restaurant", ja: "レストラン", tr: "Restoran", ar: "مطعم" }),
  с("Спа", { en: "Spa", uz: "Spa", zh: "水疗", ko: "스파", de: "Spa", fr: "Spa", ja: "スパ", tr: "Spa", ar: "سبا" }),
  с("Парковка", { en: "Parking", uz: "Avtoturargoh", zh: "停车场", ko: "주차장", de: "Parkplatz", fr: "Parking", ja: "駐車場", tr: "Otopark", ar: "موقف سيارات" }),
  с("Трансфер", { en: "Transfer", uz: "Transfer", zh: "接送", ko: "픽업 서비스", de: "Transfer", fr: "Navette", ja: "送迎", tr: "Transfer", ar: "خدمة نقل" }),
  с("Терраса", { en: "Terrace", uz: "Terrasa", zh: "露台", ko: "테라스", de: "Terrasse", fr: "Terrasse", ja: "テラス", tr: "Teras", ar: "تراس" }),
  с("Экскурсии", { en: "Tours", uz: "Ekskursiyalar", zh: "导览游", ko: "투어", de: "Touren", fr: "Excursions", ja: "ツアー", tr: "Turlar", ar: "جولات" }),
  с("Завтрак", { en: "Breakfast", uz: "Nonushta", zh: "早餐", ko: "조식", de: "Frühstück", fr: "Petit-déjeuner", ja: "朝食", tr: "Kahvaltı", ar: "إفطار" }),
  с("Бар", { en: "Bar", uz: "Bar", zh: "酒吧", ko: "바", de: "Bar", fr: "Bar", ja: "バー", tr: "Bar", ar: "بار" }),
  с("Фитнес", { en: "Fitness", uz: "Fitnes", zh: "健身房", ko: "피트니스", de: "Fitness", fr: "Fitness", ja: "フィットネス", tr: "Fitness", ar: "لياقة بدنية" }),
  с("Конференц-зал", { en: "Conference hall", uz: "Konferensiya zali", zh: "会议厅", ko: "회의실", de: "Konferenzsaal", fr: "Salle de conférence", ja: "会議室", tr: "Konferans salonu", ar: "قاعة مؤتمرات" }),
  // ── Фирменные блюда ──────────────────────────────────────────────
  с("Плов", { en: "Plov", uz: "Osh", zh: "抓饭", ko: "플로프", de: "Plov", fr: "Plov", ja: "プロフ", tr: "Plov", ar: "بلوف" }),
  с("Шашлык из баранины", { en: "Lamb shashlik", uz: "Qoʻy goʻshti shashligi", zh: "羊肉烤串", ko: "양고기 샤슬릭", de: "Lamm-Schaschlik", fr: "Chachlik d'agneau", ja: "ラムのシャシリク", tr: "Kuzu şaşlık", ar: "شواء لحم الضأن" }),
  с("Самса тандырная", { en: "Tandoor samsa", uz: "Tandir somsa", zh: "坦都尔萨姆萨", ko: "탄두르 삼사", de: "Tandoor-Samsa", fr: "Samsa au tandoor", ja: "タンドール・サムサ", tr: "Tandır somsa", ar: "سمسة التنّور" }),
  с("Лагман", { en: "Lagman", uz: "Lagʻmon", zh: "拉条子", ko: "라그만", de: "Lagman", fr: "Laghman", ja: "ラグマン", tr: "Lağman", ar: "لغمان" }),
  с("Нон горячий", { en: "Hot non bread", uz: "Issiq non", zh: "热馕", ko: "따뜻한 논빵", de: "Warmes Non-Brot", fr: "Pain non chaud", ja: "焼きたてのノン", tr: "Sıcak non", ar: "خبز نون ساخن" }),
  // ── Демо-отзыв ───────────────────────────────────────────────────
  с("Потрясающий вид. Персонал отзывчивый.", { en: "Stunning view. Attentive staff.", uz: "Ajoyib manzara. Xodimlar eʼtiborli.", zh: "景色绝美，员工热情。", ko: "전망이 환상적이고 직원이 친절해요.", de: "Atemberaubende Aussicht. Aufmerksames Personal.", fr: "Vue superbe. Personnel attentionné.", ja: "眺めが素晴らしく、スタッフも親切。", tr: "Muhteşem manzara. İlgili personel.", ar: "إطلالة رائعة وطاقم عمل متجاوب." }),
  // ── AI-гид: приветствие, подсказки, запасной ответ ───────────────
  с("Assalomu alaykum! 👋 Я ваш AI-гид. Спрашивайте всё — история, маршруты, рестораны, транспорт, валюта!", { en: "Assalomu alaykum! 👋 I'm your AI guide. Ask me anything — history, routes, restaurants, transport, currency!", uz: "Assalomu alaykum! 👋 Men sizning AI yoʻriqchingizman. Hammasini soʻrang — tarix, marshrut, restoran, transport, valyuta!", zh: "Assalomu alaykum！👋 我是您的 AI 向导。历史、路线、餐厅、交通、汇率——尽管问我！", ko: "Assalomu alaykum! 👋 저는 당신의 AI 가이드입니다. 역사·경로·맛집·교통·환율 무엇이든 물어보세요!", de: "Assalomu alaykum! 👋 Ich bin Ihr KI-Guide. Fragen Sie alles — Geschichte, Routen, Restaurants, Transport, Währung!", fr: "Assalomu alaykum ! 👋 Je suis votre guide IA. Demandez-moi tout — histoire, itinéraires, restaurants, transport, change !", ja: "Assalomu alaykum！👋 私はあなたのAIガイドです。歴史・ルート・レストラン・交通・両替、何でも聞いてください！", tr: "Assalomu alaykum! 👋 Ben yapay zekâ rehberinizim. Her şeyi sorun — tarih, rota, restoran, ulaşım, döviz!", ar: "السلام عليكم! 👋 أنا دليلك الذكي. اسألني عن أي شيء — التاريخ، المسارات، المطاعم، النقل، العملة!" }),
  с("Спросите что угодно…", { en: "Ask anything…", uz: "Istalgan narsani soʻrang…", zh: "问点什么吧…", ko: "무엇이든 물어보세요…", de: "Fragen Sie irgendetwas…", fr: "Demandez ce que vous voulez…", ja: "何でも聞いてください…", tr: "İstediğinizi sorun…", ar: "اسأل عن أي شيء…" }),
  с("Отличный вопрос! Рекомендую посещать рано утром — свет, тишина, минимум туристов.", { en: "Great question! I'd go early in the morning — best light, quiet, and few tourists.", uz: "Ajoyib savol! Erta tongda borishni tavsiya qilaman — yorugʻlik, sokinlik va kam turist.", zh: "好问题！建议清晨前往——光线好、安静、游客少。", ko: "좋은 질문이에요! 이른 아침을 추천해요 — 빛도 좋고 조용하며 관광객도 적어요.", de: "Gute Frage! Am besten früh am Morgen — schönes Licht, Ruhe und wenige Touristen.", fr: "Bonne question ! J'irais tôt le matin — belle lumière, calme et peu de touristes.", ja: "いい質問ですね！早朝がおすすめです——光がきれいで静かで観光客も少ないです。", tr: "Güzel soru! Sabah erken gitmenizi öneririm — ışık güzel, sessiz ve az turist olur.", ar: "سؤال ممتاز! أنصح بالزيارة في الصباح الباكر — إضاءة جميلة وهدوء وقلّة سيّاح." }),
  // ── AI-гид: ответы ───────────────────────────────────────────────
  с("📍 Рядом с Регистаном:\n\n🕌 Биби-Ханым — 800 м\n🏺 Музей Афросиаб — 1.2 км\n🛍️ Базар Сиаб — 900 м\n\nВключить аудиогид?", { en: "📍 Near the Registan:\n\n🕌 Bibi-Khanym — 800 m\n🏺 Afrosiyob Museum — 1.2 km\n🛍️ Siab Bazaar — 900 m\n\nStart the audio guide?", uz: "📍 Registon yaqinida:\n\n🕌 Bibi Xonim — 800 m\n🏺 Afrosiyob muzeyi — 1.2 km\n🛍️ Siyob bozori — 900 m\n\nAudio yoʻriqchi yoqilsinmi?", zh: "📍 雷吉斯坦附近：\n\n🕌 比比哈努姆 — 800 米\n🏺 阿夫罗夏布博物馆 — 1.2 公里\n🛍️ 夏布集市 — 900 米\n\n要开启语音导览吗？", ko: "📍 레기스탄 근처:\n\n🕌 비비하늠 — 800 m\n🏺 아프로시욥 박물관 — 1.2 km\n🛍️ 시압 시장 — 900 m\n\n오디오 가이드를 켤까요?", de: "📍 Nahe dem Registan:\n\n🕌 Bibi-Chanym — 800 m\n🏺 Afrosiyob-Museum — 1,2 km\n🛍️ Siab-Basar — 900 m\n\nAudioguide starten?", fr: "📍 Près du Reguistan :\n\n🕌 Bibi-Khanym — 800 m\n🏺 Musée Afrosiyob — 1,2 km\n🛍️ Bazar Siab — 900 m\n\nLancer l'audioguide ?", ja: "📍 レギスタン周辺：\n\n🕌 ビビハニム — 800 m\n🏺 アフロシヨブ博物館 — 1.2 km\n🛍️ シアブ・バザール — 900 m\n\n音声ガイドを開始しますか？", tr: "📍 Registan yakınında:\n\n🕌 Bibi-Hanım — 800 m\n🏺 Afrosiyob Müzesi — 1,2 km\n🛍️ Siab Pazarı — 900 m\n\nSesli rehber açılsın mı?", ar: "📍 قرب ريغستان:\n\n🕌 بيبي خانم — 800 م\n🏺 متحف أفروسياب — 1.2 كم\n🛍️ سوق سياب — 900 م\n\nهل نبدأ الدليل الصوتي؟" }),
  с("🏛️ Регистан — «Песчаное место».\n\nТри медресе: Улугбека (1420), Шер-Дор (1636) и Тилля-Кари (1660). Тамерлан выбрал это место как имперский центр.", { en: "🏛️ Registan — 'the sandy place'.\n\nThree madrasahs: Ulugbek (1420), Sher-Dor (1636) and Tilla-Kari (1660). Tamerlane chose this spot as his imperial centre.", uz: "🏛️ Registon — «qumli joy».\n\nUch madrasa: Ulugʻbek (1420), Sherdor (1636) va Tillakori (1660). Amir Temur bu joyni imperiya markazi qilib tanlagan.", zh: "🏛️ 雷吉斯坦——意为“沙地”。\n\n三座经学院：乌鲁伯格（1420）、希尔多（1636）与提拉卡里（1660）。帖木儿选定此地为帝国中心。", ko: "🏛️ 레기스탄 — '모래의 광장'.\n\n세 마드라사: 울루그베크(1420), 셰르도르(1636), 틸라카리(1660). 티무르가 제국의 중심지로 택한 곳.", de: "🏛️ Registan — „der sandige Ort“.\n\nDrei Medresen: Ulugbek (1420), Sher-Dor (1636) und Tilla-Kari (1660). Timur wählte diesen Ort als Reichszentrum.", fr: "🏛️ Reguistan — « le lieu de sable ».\n\nTrois madrasas : Ulugh Beg (1420), Cher-Dor (1636) et Tilla-Kari (1660). Tamerlan en fit son centre impérial.", ja: "🏛️ レギスタン——「砂の場所」。\n\n三つのマドラサ：ウルグベク（1420）、シェルドル（1636）、ティラカリ（1660）。ティムールが帝国の中心に選んだ地。", tr: "🏛️ Registan — «kumlu yer».\n\nÜç medrese: Uluğ Bey (1420), Şirdar (1636) ve Tillakâri (1660). Timur burayı imparatorluk merkezi seçti.", ar: "🏛️ ريغستان — «المكان الرملي».\n\nثلاث مدارس: أولوغ بيك (1420) وشيردور (1636) وتيلا كاري (1660). اختاره تيمورلنك مركزاً لإمبراطوريته." }),
  с("🍽️ Топ рестораны:\n\n1. Platan — лучший плов $8–15\n2. Nargis — терраса с видом $5–12\n3. Silk Road Spices — фьюжн $12–20\n\n💡 Плов едят до полудня!", { en: "🍽️ Top restaurants:\n\n1. Platan — best plov $8–15\n2. Nargis — terrace with a view $5–12\n3. Silk Road Spices — fusion $12–20\n\n💡 Plov is eaten before noon!", uz: "🍽️ Eng zoʻr restoranlar:\n\n1. Platan — eng zoʻr osh $8–15\n2. Nargis — manzarali terrasa $5–12\n3. Silk Road Spices — fyujn $12–20\n\n💡 Osh tushgacha yeyiladi!", zh: "🍽️ 顶级餐厅：\n\n1. Platan — 最佳抓饭 $8–15\n2. Nargis — 观景露台 $5–12\n3. Silk Road Spices — 融合菜 $12–20\n\n💡 抓饭要在午前吃！", ko: "🍽️ 인기 맛집:\n\n1. Platan — 최고의 플로프 $8–15\n2. Nargis — 전망 테라스 $5–12\n3. Silk Road Spices — 퓨전 $12–20\n\n💡 플로프는 정오 전에 먹어요!", de: "🍽️ Top-Restaurants:\n\n1. Platan — bester Plov 8–15 $\n2. Nargis — Terrasse mit Blick 5–12 $\n3. Silk Road Spices — Fusion 12–20 $\n\n💡 Plov isst man vormittags!", fr: "🍽️ Meilleurs restaurants :\n\n1. Platan — meilleur plov 8–15 $\n2. Nargis — terrasse avec vue 5–12 $\n3. Silk Road Spices — fusion 12–20 $\n\n💡 Le plov se mange avant midi !", ja: "🍽️ おすすめレストラン：\n\n1. Platan — 絶品プロフ $8–15\n2. Nargis — 眺めのよいテラス $5–12\n3. Silk Road Spices — フュージョン $12–20\n\n💡 プロフは正午前に！", tr: "🍽️ En iyi restoranlar:\n\n1. Platan — en iyi plov $8–15\n2. Nargis — manzaralı teras $5–12\n3. Silk Road Spices — füzyon $12–20\n\n💡 Plov öğleden önce yenir!", ar: "🍽️ أفضل المطاعم:\n\n1. Platan — أفضل بلوف $8–15\n2. Nargis — تراس بإطلالة $5–12\n3. Silk Road Spices — مطبخ مندمج $12–20\n\n💡 يؤكل البلوف قبل الظهر!" }),
  с("🎫 Бесплатно:\n\n✅ Внешний Регистан\n✅ Минарет Калян\n✅ Стены Ичан-Калы\n✅ Базар Чорсу\n✅ Площадь Мустакиллик\n✅ Чарвак", { en: "🎫 Free:\n\n✅ Registan exterior\n✅ Kalyan Minaret\n✅ Ichan-Kala walls\n✅ Chorsu Bazaar\n✅ Mustaqillik Square\n✅ Charvak", uz: "🎫 Bepul:\n\n✅ Registonning tashqarisi\n✅ Kalon minorasi\n✅ Ichan Qalʼa devorlari\n✅ Chorsu bozori\n✅ Mustaqillik maydoni\n✅ Chorvoq", zh: "🎫 免费：\n\n✅ 雷吉斯坦外景\n✅ 卡扬宣礼塔\n✅ 伊禅卡拉城墙\n✅ 乔尔苏集市\n✅ 独立广场\n✅ 恰尔瓦克", ko: "🎫 무료:\n\n✅ 레기스탄 외부\n✅ 칼란 미너렛\n✅ 이찬칼라 성벽\n✅ 초르수 시장\n✅ 무스타킬리크 광장\n✅ 차르바크", de: "🎫 Kostenlos:\n\n✅ Registan von außen\n✅ Kalyan-Minarett\n✅ Mauern von Itschan Qalʼa\n✅ Chorsu-Basar\n✅ Mustaqillik-Platz\n✅ Tscharwak", fr: "🎫 Gratuit :\n\n✅ Extérieur du Reguistan\n✅ Minaret Kalian\n✅ Remparts d'Itchan Kala\n✅ Bazar Chorsu\n✅ Place Moustaqillik\n✅ Tcharvak", ja: "🎫 無料：\n\n✅ レギスタン外観\n✅ カラーン・ミナレット\n✅ イチャン・カラの城壁\n✅ チョルスー・バザール\n✅ ムスタキリク広場\n✅ チャルヴァク", tr: "🎫 Ücretsiz:\n\n✅ Registan'ın dışı\n✅ Kalyan Minaresi\n✅ İçan Kale surları\n✅ Çorsu Pazarı\n✅ Mustakillik Meydanı\n✅ Çarvak", ar: "🎫 مجاناً:\n\n✅ ريغستان من الخارج\n✅ مئذنة كليان\n✅ أسوار إيتشان قلعة\n✅ سوق تشورسو\n✅ ساحة مستقلليك\n✅ تشارفاك" }),
  с("🚂 Самарканд→Бухара:\n\n🚄 Поезд: 1.5 ч, от $12\n🚌 Маршрутка: 2 ч, от $5\n\nОтправление: 06:20, 10:45, 14:30, 18:00", { en: "🚂 Samarkand→Bukhara:\n\n🚄 Train: 1.5 h, from $12\n🚌 Shared van: 2 h, from $5\n\nDepartures: 06:20, 10:45, 14:30, 18:00", uz: "🚂 Samarqand→Buxoro:\n\n🚄 Poyezd: 1.5 soat, $12 dan\n🚌 Marshrutka: 2 soat, $5 dan\n\nJoʻnash: 06:20, 10:45, 14:30, 18:00", zh: "🚂 撒马尔罕→布哈拉：\n\n🚄 火车：1.5 小时，$12 起\n🚌 小巴：2 小时，$5 起\n\n发车：06:20、10:45、14:30、18:00", ko: "🚂 사마르칸트→부하라:\n\n🚄 기차: 1.5시간, $12부터\n🚌 합승 밴: 2시간, $5부터\n\n출발: 06:20, 10:45, 14:30, 18:00", de: "🚂 Samarkand→Buchara:\n\n🚄 Zug: 1,5 Std., ab 12 $\n🚌 Sammeltaxi: 2 Std., ab 5 $\n\nAbfahrten: 06:20, 10:45, 14:30, 18:00", fr: "🚂 Samarcande→Boukhara :\n\n🚄 Train : 1,5 h, dès 12 $\n🚌 Minibus : 2 h, dès 5 $\n\nDéparts : 06:20, 10:45, 14:30, 18:00", ja: "🚂 サマルカンド→ブハラ：\n\n🚄 列車：1.5時間、$12〜\n🚌 乗合バン：2時間、$5〜\n\n出発：06:20、10:45、14:30、18:00", tr: "🚂 Semerkant→Buhara:\n\n🚄 Tren: 1,5 saat, $12'den\n🚌 Dolmuş: 2 saat, $5'ten\n\nKalkışlar: 06:20, 10:45, 14:30, 18:00", ar: "🚂 سمرقند→بخارى:\n\n🚄 قطار: 1.5 ساعة، من $12\n🚌 حافلة صغيرة: ساعتان، من $5\n\nالمواعيد: 06:20، 10:45، 14:30، 18:00" }),
  с("🏨 Отели:\n\n⭐ Registan Plaza $89 · 4.8★\n⭐ Malika Premier $65 · 4.6★\n⭐ B&B Guestus $35 · 4.7★\n\nСкидка 10% через UzUp!", { en: "🏨 Hotels:\n\n⭐ Registan Plaza $89 · 4.8★\n⭐ Malika Premier $65 · 4.6★\n⭐ B&B Guestus $35 · 4.7★\n\n10% off via UzUp!", uz: "🏨 Mehmonxonalar:\n\n⭐ Registan Plaza $89 · 4.8★\n⭐ Malika Premier $65 · 4.6★\n⭐ B&B Guestus $35 · 4.7★\n\nUzUp orqali 10% chegirma!", zh: "🏨 酒店：\n\n⭐ Registan Plaza $89 · 4.8★\n⭐ Malika Premier $65 · 4.6★\n⭐ B&B Guestus $35 · 4.7★\n\n通过 UzUp 享 9 折！", ko: "🏨 호텔:\n\n⭐ Registan Plaza $89 · 4.8★\n⭐ Malika Premier $65 · 4.6★\n⭐ B&B Guestus $35 · 4.7★\n\nUzUp로 10% 할인!", de: "🏨 Hotels:\n\n⭐ Registan Plaza 89 $ · 4,8★\n⭐ Malika Premier 65 $ · 4,6★\n⭐ B&B Guestus 35 $ · 4,7★\n\n10% Rabatt über UzUp!", fr: "🏨 Hôtels :\n\n⭐ Registan Plaza 89 $ · 4,8★\n⭐ Malika Premier 65 $ · 4,6★\n⭐ B&B Guestus 35 $ · 4,7★\n\n−10% via UzUp !", ja: "🏨 ホテル：\n\n⭐ Registan Plaza $89 · 4.8★\n⭐ Malika Premier $65 · 4.6★\n⭐ B&B Guestus $35 · 4.7★\n\nUzUpで10%オフ！", tr: "🏨 Oteller:\n\n⭐ Registan Plaza $89 · 4.8★\n⭐ Malika Premier $65 · 4.6★\n⭐ B&B Guestus $35 · 4.7★\n\nUzUp ile %10 indirim!", ar: "🏨 الفنادق:\n\n⭐ Registan Plaza $89 · 4.8★\n⭐ Malika Premier $65 · 4.6★\n⭐ B&B Guestus $35 · 4.7★\n\nخصم 10% عبر UzUp!" }),
  с("🌙 Вечер:\n\n✨ 19:00 Световое шоу Регистан $15\n🍽️ 20:30 Ужин в Platan\n🌟 22:00 Ночная прогулка", { en: "🌙 Evening:\n\n✨ 19:00 Registan light show $15\n🍽️ 20:30 Dinner at Platan\n🌟 22:00 Night walk", uz: "🌙 Kechqurun:\n\n✨ 19:00 Registon yorugʻlik shousi $15\n🍽️ 20:30 Platanda kechki ovqat\n🌟 22:00 Tungi sayr", zh: "🌙 夜晚：\n\n✨ 19:00 雷吉斯坦灯光秀 $15\n🍽️ 20:30 Platan 晚餐\n🌟 22:00 夜间漫步", ko: "🌙 저녁:\n\n✨ 19:00 레기스탄 라이트 쇼 $15\n🍽️ 20:30 Platan에서 저녁\n🌟 22:00 야간 산책", de: "🌙 Abend:\n\n✨ 19:00 Registan-Lichtshow 15 $\n🍽️ 20:30 Abendessen im Platan\n🌟 22:00 Nachtspaziergang", fr: "🌙 Soirée :\n\n✨ 19:00 spectacle de lumière au Reguistan 15 $\n🍽️ 20:30 dîner au Platan\n🌟 22:00 balade nocturne", ja: "🌙 夜：\n\n✨ 19:00 レギスタンのライトショー $15\n🍽️ 20:30 Platanで夕食\n🌟 22:00 ナイトウォーク", tr: "🌙 Akşam:\n\n✨ 19:00 Registan ışık gösterisi $15\n🍽️ 20:30 Platan'da akşam yemeği\n🌟 22:00 Gece yürüyüşü", ar: "🌙 المساء:\n\n✨ 19:00 عرض ريغستان الضوئي $15\n🍽️ 20:30 عشاء في Platan\n🌟 22:00 نزهة ليلية" }),
  с("💱 Курс:\n\n$1 = 12 740 UZS\n€1 = 13 980 UZS\n₽1 = 138 UZS\n\n💡 Меняйте в банке, не у менял.", { en: "💱 Rate:\n\n$1 = 12,740 UZS\n€1 = 13,980 UZS\n₽1 = 138 UZS\n\n💡 Exchange at a bank, not with street changers.", uz: "💱 Kurs:\n\n$1 = 12 740 soʻm\n€1 = 13 980 soʻm\n₽1 = 138 soʻm\n\n💡 Bankda ayirboshlang, koʻchada emas.", zh: "💱 汇率：\n\n$1 = 12 740 苏姆\n€1 = 13 980 苏姆\n₽1 = 138 苏姆\n\n💡 请在银行兑换，别找街头换钱人。", ko: "💱 환율:\n\n$1 = 12,740 숨\n€1 = 13,980 숨\n₽1 = 138 숨\n\n💡 길거리 환전상 말고 은행에서 바꾸세요.", de: "💱 Kurs:\n\n$1 = 12.740 UZS\n€1 = 13.980 UZS\n₽1 = 138 UZS\n\n💡 In der Bank wechseln, nicht bei Straßenhändlern.", fr: "💱 Taux :\n\n$1 = 12 740 UZS\n€1 = 13 980 UZS\n₽1 = 138 UZS\n\n💡 Changez à la banque, pas dans la rue.", ja: "💱 レート：\n\n$1 = 12,740 スム\n€1 = 13,980 スム\n₽1 = 138 スム\n\n💡 両替は銀行で、路上の両替人は避けて。", tr: "💱 Kur:\n\n$1 = 12.740 UZS\n€1 = 13.980 UZS\n₽1 = 138 UZS\n\n💡 Sokaktaki değil, bankada bozdurun.", ar: "💱 السعر:\n\n$1 = 12,740 سوم\n€1 = 13,980 سوم\n₽1 = 138 سوم\n\n💡 بدّل في البنك لا مع صيارفة الشارع." }),
  с("🚌 Транспорт:\n\n🚖 Яндекс.Такси ~$1–3\n🚌 Автобус 22 UZS\n🚶 Пешком 20–40 мин между достопримечательностями", { en: "🚌 Transport:\n\n🚖 Yandex Taxi ~$1–3\n🚌 Bus 22 UZS\n🚶 20–40 min on foot between the sights", uz: "🚌 Transport:\n\n🚖 Yandex Taksi ~$1–3\n🚌 Avtobus 22 soʻm\n🚶 Diqqatga sazovor joylar orasida 20–40 daqiqa piyoda", zh: "🚌 交通：\n\n🚖 Yandex 打车 ~$1–3\n🚌 公交 22 苏姆\n🚶 景点之间步行 20–40 分钟", ko: "🚌 교통:\n\n🚖 얀덱스 택시 ~$1–3\n🚌 버스 22 숨\n🚶 명소 사이 도보 20–40분", de: "🚌 Transport:\n\n🚖 Yandex Taxi ~1–3 $\n🚌 Bus 22 UZS\n🚶 20–40 Min. zu Fuß zwischen den Sehenswürdigkeiten", fr: "🚌 Transport :\n\n🚖 Yandex Taxi ~1–3 $\n🚌 Bus 22 UZS\n🚶 20–40 min à pied entre les sites", ja: "🚌 交通：\n\n🚖 Yandexタクシー ~$1–3\n🚌 バス 22スム\n🚶 名所間は徒歩20〜40分", tr: "🚌 Ulaşım:\n\n🚖 Yandex Taksi ~$1–3\n🚌 Otobüs 22 UZS\n🚶 Görülecek yerler arası 20–40 dk yürüyüş", ar: "🚌 النقل:\n\n🚖 Yandex Taxi ~$1–3\n🚌 حافلة 22 سوم\n🚶 20–40 دقيقة سيراً بين المعالم" }),
  // ── Маршруты: названия, ярлыки, подзаголовки ─────────────────────
  с("Самарканд за 1 день", { en: "Samarkand in 1 day", uz: "Samarqand 1 kunda", zh: "一日撒马尔罕", ko: "하루 사마르칸트", de: "Samarkand an 1 Tag", fr: "Samarcande en 1 jour", ja: "1日サマルカンド", tr: "1 Günde Semerkant", ar: "سمرقند في يوم" }),
  с("Великий Шёлковый путь", { en: "The Great Silk Road", uz: "Buyuk Ipak yoʻli", zh: "伟大的丝绸之路", ko: "위대한 실크로드", de: "Die Große Seidenstraße", fr: "La grande Route de la soie", ja: "偉大なるシルクロード", tr: "Büyük İpek Yolu", ar: "طريق الحرير العظيم" }),
  с("Гастрономический", { en: "Culinary", uz: "Gastronomik", zh: "美食之旅", ko: "미식 여행", de: "Kulinarisch", fr: "Gastronomique", ja: "グルメ", tr: "Gastronomik", ar: "رحلة الطعام" }),
  с("Исламское наследие", { en: "Islamic heritage", uz: "Islom merosi", zh: "伊斯兰遗产", ko: "이슬람 유산", de: "Islamisches Erbe", fr: "Patrimoine islamique", ja: "イスラムの遺産", tr: "İslami miras", ar: "التراث الإسلامي" }),
  с("14 дней по Узбекистану", { en: "14 days across Uzbekistan", uz: "Oʻzbekiston boʻylab 14 kun", zh: "乌兹别克斯坦14日游", ko: "우즈베키스탄 14일", de: "14 Tage durch Usbekistan", fr: "14 jours à travers l'Ouzbékistan", ja: "ウズベキスタン14日間", tr: "14 Günde Özbekistan", ar: "14 يوماً عبر أوزبكستان" }),
  с("Горный Узбекистан", { en: "Mountain Uzbekistan", uz: "Togʻli Oʻzbekiston", zh: "山地乌兹别克斯坦", ko: "산악 우즈베키스탄", de: "Bergiges Usbekistan", fr: "L'Ouzbékistan montagnard", ja: "山岳ウズベキスタン", tr: "Dağlık Özbekistan", ar: "أوزبكستان الجبلية" }),
  с("Классика", { en: "Classic", uz: "Klassika", zh: "经典", ko: "클래식", de: "Klassiker", fr: "Classique", ja: "定番", tr: "Klasik", ar: "كلاسيكي" }),
  с("Эпик", { en: "Epic", uz: "Epik", zh: "史诗", ko: "에픽", de: "Episch", fr: "Épique", ja: "エピック", tr: "Epik", ar: "ملحمي" }),
  с("Еда", { en: "Food", uz: "Taom", zh: "美食", ko: "음식", de: "Essen", fr: "Cuisine", ja: "グルメ", tr: "Yemek", ar: "طعام" }),
  с("Культура", { en: "Culture", uz: "Madaniyat", zh: "文化", ko: "문화", de: "Kultur", fr: "Culture", ja: "文化", tr: "Kültür", ar: "ثقافة" }),
  с("Полный", { en: "Full", uz: "Toʻliq", zh: "全程", ko: "완전판", de: "Komplett", fr: "Complet", ja: "フル", tr: "Tam", ar: "شامل" }),
  с("5 мест · 12 км · ~$26", { en: "5 places · 12 km · ~$26", uz: "5 joy · 12 km · ~$26", zh: "5 处 · 12 公里 · ~$26", ko: "5곳 · 12 km · ~$26", de: "5 Orte · 12 km · ~26 $", fr: "5 lieux · 12 km · ~26 $", ja: "5か所 · 12 km · ~$26", tr: "5 yer · 12 km · ~$26", ar: "5 أماكن · 12 كم · ~$26" }),
  с("22 остановки · 1400 км", { en: "22 stops · 1,400 km", uz: "22 bekat · 1400 km", zh: "22 站 · 1400 公里", ko: "22개 정차 · 1,400 km", de: "22 Stopps · 1.400 km", fr: "22 étapes · 1 400 km", ja: "22か所 · 1,400 km", tr: "22 durak · 1.400 km", ar: "22 محطة · 1400 كم" }),
  с("14 остановок · 820 км", { en: "14 stops · 820 km", uz: "14 bekat · 820 km", zh: "14 站 · 820 公里", ko: "14개 정차 · 820 km", de: "14 Stopps · 820 km", fr: "14 étapes · 820 km", ja: "14か所 · 820 km", tr: "14 durak · 820 km", ar: "14 محطة · 820 كم" }),
  с("18 остановок · 980 км", { en: "18 stops · 980 km", uz: "18 bekat · 980 km", zh: "18 站 · 980 公里", ko: "18개 정차 · 980 km", de: "18 Stopps · 980 km", fr: "18 étapes · 980 km", ja: "18か所 · 980 km", tr: "18 durak · 980 km", ar: "18 محطة · 980 كم" }),
  с("48 остановок · 2800 км", { en: "48 stops · 2,800 km", uz: "48 bekat · 2800 km", zh: "48 站 · 2800 公里", ko: "48개 정차 · 2,800 km", de: "48 Stopps · 2.800 km", fr: "48 étapes · 2 800 km", ja: "48か所 · 2,800 km", tr: "48 durak · 2.800 km", ar: "48 محطة · 2800 كم" }),
  с("8 мест · 340 км", { en: "8 places · 340 km", uz: "8 joy · 340 km", zh: "8 处 · 340 公里", ko: "8곳 · 340 km", de: "8 Orte · 340 km", fr: "8 lieux · 340 km", ja: "8か所 · 340 km", tr: "8 yer · 340 km", ar: "8 أماكن · 340 كم" }),
  // ── События ──────────────────────────────────────────────────────
  с("Фестиваль Навруз", { en: "Navruz Festival", uz: "Navroʻz bayrami", zh: "纳吾肉孜节", ko: "나브루즈 축제", de: "Navruz-Fest", fr: "Festival de Navrouz", ja: "ナヴルーズ祭", tr: "Nevruz Festivali", ar: "مهرجان النوروز" }),
  с("Персидский Новый год — музыка, сумаляк, народные гуляния.", { en: "The Persian New Year — music, sumalak and folk festivities.", uz: "Fors yangi yili — musiqa, sumalak, xalq sayllari.", zh: "波斯新年——音乐、苏马拉克与民间庆典。", ko: "페르시아 새해 — 음악, 수말락, 민속 축제.", de: "Das persische Neujahr — Musik, Sumalak und Volksfeste.", fr: "Le Nouvel An perse — musique, soumalak et fêtes populaires.", ja: "ペルシャ暦の新年——音楽、スマラク、民衆の祝祭。", tr: "Fars Yeni Yılı — müzik, sümelek ve halk şenlikleri.", ar: "رأس السنة الفارسية — موسيقى وسمالك واحتفالات شعبية." }),
  с("Шёлковый путь: музыка", { en: "Silk Road: Music", uz: "Ipak yoʻli: musiqa", zh: "丝绸之路：音乐", ko: "실크로드: 음악", de: "Seidenstraße: Musik", fr: "Route de la soie : musique", ja: "シルクロード：音楽", tr: "İpek Yolu: Müzik", ar: "طريق الحرير: الموسيقى" }),
  с("Международный фестиваль традиционной музыки у стен Регистана.", { en: "An international festival of traditional music at the walls of the Registan.", uz: "Registon devorlari yonida anʼanaviy musiqa xalqaro festivali.", zh: "在雷吉斯坦城墙下举办的国际传统音乐节。", ko: "레기스탄 성벽 아래에서 열리는 국제 전통 음악 축제.", de: "Ein internationales Festival traditioneller Musik an den Mauern des Registan.", fr: "Un festival international de musique traditionnelle au pied du Reguistan.", ja: "レギスタンの城壁のもとで開かれる国際伝統音楽祭。", tr: "Registan surlarının dibinde uluslararası geleneksel müzik festivali.", ar: "مهرجان دولي للموسيقى التقليدية عند أسوار ريغستان." }),
  с("Гастрофест «Плов»", { en: "'Plov' Food Festival", uz: "«Osh» gastrofestivali", zh: "“抓饭”美食节", ko: "'플로프' 음식 축제", de: "Gastro-Fest „Plov“", fr: "Festival gastronomique « Plov »", ja: "グルメ祭「プロフ」", tr: "«Plov» Gastro Festivali", ar: "مهرجان «البلوف» للطعام" }),
  с("Соревнование поваров — более 100 видов плова со всего Узбекистана.", { en: "A chefs' competition — over 100 kinds of plov from across Uzbekistan.", uz: "Oshpazlar bellashuvi — Oʻzbekiston boʻylab 100 dan ortiq osh turi.", zh: "厨师大赛——汇集乌兹别克斯坦各地 100 多种抓饭。", ko: "요리사 경연 — 우즈베키스탄 전역의 플로프 100여 종.", de: "Ein Köchewettbewerb — über 100 Plov-Sorten aus ganz Usbekistan.", fr: "Un concours de chefs — plus de 100 sortes de plov de tout l'Ouzbékistan.", ja: "料理人の腕くらべ——ウズベキスタン各地から100種類以上のプロフ。", tr: "Aşçı yarışması — Özbekistan'ın dört bir yanından 100'den fazla plov çeşidi.", ar: "مسابقة طهاة — أكثر من 100 نوع بلوف من كل أنحاء أوزبكستان." }),
  с("Буз-кашши", { en: "Buzkashi", uz: "Uloq (koʻpkari)", zh: "叼羊", ko: "부즈카시", de: "Buzkaschi", fr: "Bouzkachi", ja: "ブズカシ", tr: "Buzkaşi (Kökbörü)", ar: "بوزكاشي" }),
  с("Традиционная конная игра — зрелищный народный спорт.", { en: "A traditional horseback game — a spectacular folk sport.", uz: "Anʼanaviy ot oʻyini — koʻrkam xalq sporti.", zh: "传统马上竞技——精彩的民间运动。", ko: "전통 기마 경기 — 박진감 넘치는 민속 스포츠.", de: "Ein traditionelles Reiterspiel — ein spektakulärer Volkssport.", fr: "Un jeu équestre traditionnel — un sport populaire spectaculaire.", ja: "伝統的な馬上競技——迫力ある民衆スポーツ。", tr: "Geleneksel atlı oyun — görkemli bir halk sporu.", ar: "لعبة تقليدية على ظهور الخيل — رياضة شعبية مثيرة." }),
  // ── Маршруты: заметки к остановкам ───────────────────────────────
  с("Лучший свет для фото", { en: "Best light for photos", uz: "Surat uchun eng yaxshi yorugʻlik", zh: "最佳拍照光线", ko: "사진 찍기 좋은 빛", de: "Bestes Licht für Fotos", fr: "Meilleure lumière pour les photos", ja: "写真に最適な光", tr: "Fotoğraf için en iyi ışık", ar: "أفضل إضاءة للصور" }),
  с("5 мин пешком", { en: "5 min on foot", uz: "5 daqiqa piyoda", zh: "步行5分钟", ko: "도보 5분", de: "5 Min. zu Fuß", fr: "5 min à pied", ja: "徒歩5分", tr: "5 dk yürüyüş", ar: "5 دقائق سيراً" }),
  с("Нон и сухофрукты", { en: "Non bread and dried fruit", uz: "Non va quruq meva", zh: "馕与果干", ko: "논빵과 말린 과일", de: "Non-Brot und Trockenobst", fr: "Pain non et fruits secs", ja: "ノンとドライフルーツ", tr: "Non ekmeği ve kuru meyve", ar: "خبز نون وفواكه مجفّفة" }),
  с("Послеполуденный свет", { en: "Afternoon light", uz: "Tushdan keyingi yorugʻlik", zh: "午后光线", ko: "오후의 빛", de: "Nachmittagslicht", fr: "Lumière de l'après-midi", ja: "午後の光", tr: "Öğleden sonra ışığı", ar: "ضوء ما بعد الظهر" }),
  с("Такси 15 мин", { en: "15 min by taxi", uz: "Taksida 15 daqiqa", zh: "打车15分钟", ko: "택시 15분", de: "15 Min. mit dem Taxi", fr: "15 min en taxi", ja: "タクシーで15分", tr: "Taksiyle 15 dk", ar: "15 دقيقة بالتاكسي" }),
  с("Поезд Афросиаб 2 ч", { en: "Afrosiyob train, 2 h", uz: "Afrosiyob poyezdi, 2 soat", zh: "阿夫罗夏布号火车 2 小时", ko: "아프로시욥 기차 2시간", de: "Afrosiyob-Zug, 2 Std.", fr: "Train Afrosiyob, 2 h", ja: "アフロシヨブ号 2時間", tr: "Afrosiyob treni, 2 saat", ar: "قطار أفروسياب، ساعتان" }),
  с("Сердце Шёлкового пути", { en: "Heart of the Silk Road", uz: "Ipak yoʻlining yuragi", zh: "丝绸之路的心脏", ko: "실크로드의 심장", de: "Herz der Seidenstraße", fr: "Cœur de la Route de la soie", ja: "シルクロードの心臓部", tr: "İpek Yolu'nun kalbi", ar: "قلب طريق الحرير" }),
  с("Поезд 1.5 ч", { en: "Train, 1.5 h", uz: "Poyezd, 1.5 soat", zh: "火车 1.5 小时", ko: "기차 1.5시간", de: "Zug, 1,5 Std.", fr: "Train, 1,5 h", ja: "列車 1.5時間", tr: "Tren, 1,5 saat", ar: "قطار، 1.5 ساعة" }),
  с("Арк, Калян, Ляби-Хауз", { en: "Ark, Kalyan, Lyabi-Hauz", uz: "Ark, Kalon, Labi Hovuz", zh: "方舟城堡、卡扬、拉比豪兹", ko: "아르크, 칼란, 라비하우즈", de: "Ark, Kalyan, Lyabi-Hauz", fr: "Ark, Kalian, Lyabi-Haouz", ja: "アルク、カラーン、ラビハウズ", tr: "Ark, Kalyan, Lyabi-Havuz", ar: "الأرك، كليان، لبّي حوض" }),
  с("Переезд 5 ч", { en: "5 h transfer", uz: "5 soatlik yoʻl", zh: "转场5小时", ko: "이동 5시간", de: "5 Std. Überfahrt", fr: "Trajet de 5 h", ja: "移動5時間", tr: "5 saatlik yolculuk", ar: "انتقال 5 ساعات" }),
  с("Лучший плов в стране", { en: "The country's best plov", uz: "Mamlakatdagi eng zoʻr osh", zh: "全国最好的抓饭", ko: "전국 최고의 플로프", de: "Der beste Plov des Landes", fr: "Le meilleur plov du pays", ja: "国内一のプロフ", tr: "Ülkenin en iyi plovu", ar: "أفضل بلوف في البلاد" }),
  с("Специи, орехи, сухофрукты", { en: "Spices, nuts, dried fruit", uz: "Ziravorlar, yongʻoq, quruq meva", zh: "香料、坚果、果干", ko: "향신료, 견과, 말린 과일", de: "Gewürze, Nüsse, Trockenobst", fr: "Épices, noix, fruits secs", ja: "香辛料、ナッツ、ドライフルーツ", tr: "Baharat, kuruyemiş, kuru meyve", ar: "توابل ومكسّرات وفواكه مجفّفة" }),
  с("Научитесь лепить", { en: "Learn to shape them", uz: "Yasashni oʻrganing", zh: "学做萨姆萨", ko: "빚는 법 배우기", de: "Lernen Sie, sie zu formen", fr: "Apprenez à les façonner", ja: "包み方を習う", tr: "Yapmayı öğrenin", ar: "تعلّم تشكيلها" }),
  с("Современная кухня", { en: "Modern cuisine", uz: "Zamonaviy oshxona", zh: "现代料理", ko: "현대 요리", de: "Moderne Küche", fr: "Cuisine moderne", ja: "モダン料理", tr: "Modern mutfak", ar: "مطبخ عصري" }),
  с("Уличная еда с местными", { en: "Street food with locals", uz: "Mahalliylar bilan koʻcha taomlari", zh: "与当地人共享街头美食", ko: "현지인과 함께하는 길거리 음식", de: "Streetfood mit Einheimischen", fr: "Cuisine de rue avec les habitants", ja: "地元の人と屋台グルメ", tr: "Yerlilerle sokak lezzetleri", ar: "أكل الشارع مع الأهالي" }),
  с("Старейшая мечеть региона", { en: "The region's oldest mosque", uz: "Mintaqadagi eng qadimgi masjid", zh: "该地区最古老的清真寺", ko: "이 지역에서 가장 오래된 모스크", de: "Die älteste Moschee der Region", fr: "La plus ancienne mosquée de la région", ja: "地域最古のモスク", tr: "Bölgenin en eski camisi", ar: "أقدم مسجد في المنطقة" }),
  с("Три медресе 15–17 вв.", { en: "Three madrasahs, 15th–17th c.", uz: "Uch madrasa, XV–XVII asrlar", zh: "三座经学院，15至17世纪", ko: "세 마드라사, 15~17세기", de: "Drei Medresen, 15.–17. Jh.", fr: "Trois madrasas, XVe–XVIIe s.", ja: "三つのマドラサ、15〜17世紀", tr: "Üç medrese, 15–17. yy.", ar: "ثلاث مدارس، القرن 15–17" }),
  с("800-летний символ", { en: "An 800-year-old symbol", uz: "800 yillik ramz", zh: "800年历史的象征", ko: "800년 된 상징", de: "Ein 800 Jahre altes Wahrzeichen", fr: "Un symbole vieux de 800 ans", ja: "800年の象徴", tr: "800 yıllık simge", ar: "رمز عمره 800 عام" }),
  с("40 деревянных колонн", { en: "40 wooden columns", uz: "40 ta yogʻoch ustun", zh: "40根木柱", ko: "나무 기둥 40개", de: "40 Holzsäulen", fr: "40 colonnes de bois", ja: "40本の木柱", tr: "40 ahşap sütun", ar: "40 عموداً خشبياً" }),
  с("213 колонн XI–XIX вв.", { en: "213 columns, 11th–19th c.", uz: "213 ustun, XI–XIX asrlar", zh: "213根立柱，11至19世纪", ko: "기둥 213개, 11~19세기", de: "213 Säulen, 11.–19. Jh.", fr: "213 colonnes, XIe–XIXe s.", ja: "213本の柱、11〜19世紀", tr: "213 sütun, 11–19. yy.", ar: "213 عموداً، القرن 11–19" }),
  с("Столица и музеи", { en: "The capital and its museums", uz: "Poytaxt va muzeylar", zh: "首都与博物馆", ko: "수도와 박물관", de: "Die Hauptstadt und ihre Museen", fr: "La capitale et ses musées", ja: "首都と博物館", tr: "Başkent ve müzeler", ar: "العاصمة ومتاحفها" }),
  с("Регистан, Шахи-Зинда", { en: "Registan, Shah-i-Zinda", uz: "Registon, Shohi Zinda", zh: "雷吉斯坦、夏伊辛达", ko: "레기스탄, 샤히진다", de: "Registan, Schah-i-Sinda", fr: "Reguistan, Chah-e-Zindeh", ja: "レギスタン、シャーヒズィンダ", tr: "Registan, Şah-ı Zinde", ar: "ريغستان، شاهي زندة" }),
  с("Ичан-Кала, музеи", { en: "Ichan-Kala, museums", uz: "Ichan Qalʼa, muzeylar", zh: "伊禅卡拉、博物馆", ko: "이찬칼라, 박물관", de: "Itschan Qalʼa, Museen", fr: "Itchan Kala, musées", ja: "イチャン・カラ、博物館", tr: "İçan Kale, müzeler", ar: "إيتشان قلعة، المتاحف" }),
  с("Музей Савицкого", { en: "The Savitsky Museum", uz: "Savitskiy muzeyi", zh: "萨维茨基博物馆", ko: "사비츠키 박물관", de: "Sawizki-Museum", fr: "Musée Savitski", ja: "サヴィツキー美術館", tr: "Savitski Müzesi", ar: "متحف سافيتسكي" }),
  с("Пляж и горный воздух", { en: "Beach and mountain air", uz: "Plyaj va togʻ havosi", zh: "沙滩与山间空气", ko: "해변과 산 공기", de: "Strand und Bergluft", fr: "Plage et air de montagne", ja: "ビーチと山の空気", tr: "Plaj ve dağ havası", ar: "شاطئ وهواء الجبال" }),
  с("Трекинг и панорамы", { en: "Trekking and panoramas", uz: "Trekking va panoramalar", zh: "徒步与全景", ko: "트레킹과 파노라마", de: "Trekking und Panoramen", fr: "Randonnée et panoramas", ja: "トレッキングと絶景", tr: "Trekking ve panoramalar", ar: "تسلّق وإطلالات بانورامية" }),
  с("Живописный поход", { en: "A scenic hike", uz: "Goʻzal sayohat", zh: "风景徒步", ko: "경치 좋은 하이킹", de: "Eine malerische Wanderung", fr: "Une randonnée pittoresque", ja: "風光明媚なハイキング", tr: "Manzaralı bir yürüyüş", ar: "نزهة خلّابة" }),
  // ── Маршруты: сводные названия остановок ─────────────────────────
  с("Ташкент → Самарканд", { en: "Tashkent → Samarkand", uz: "Toshkent → Samarqand", zh: "塔什干 → 撒马尔罕", ko: "타슈켄트 → 사마르칸트", de: "Taschkent → Samarkand", fr: "Tachkent → Samarcande", ja: "タシケント → サマルカンド", tr: "Taşkent → Semerkant", ar: "طشقند ← سمرقند" }),
  с("Регистан + Шахи-Зинда", { en: "Registan + Shah-i-Zinda", uz: "Registon + Shohi Zinda", zh: "雷吉斯坦 + 夏伊辛达", ko: "레기스탄 + 샤히진다", de: "Registan + Schah-i-Sinda", fr: "Reguistan + Chah-e-Zindeh", ja: "レギスタン + シャーヒズィンダ", tr: "Registan + Şah-ı Zinde", ar: "ريغستان + شاهي زندة" }),
  с("Самарканд → Бухара", { en: "Samarkand → Bukhara", uz: "Samarqand → Buxoro", zh: "撒马尔罕 → 布哈拉", ko: "사마르칸트 → 부하라", de: "Samarkand → Buchara", fr: "Samarcande → Boukhara", ja: "サマルカンド → ブハラ", tr: "Semerkant → Buhara", ar: "سمرقند ← بخارى" }),
  с("Старый город Бухары", { en: "Bukhara old town", uz: "Buxoro eski shahri", zh: "布哈拉老城", ko: "부하라 구시가지", de: "Bucharas Altstadt", fr: "Vieille ville de Boukhara", ja: "ブハラ旧市街", tr: "Buhara eski şehri", ar: "مدينة بخارى القديمة" }),
  с("Бухара → Хива", { en: "Bukhara → Khiva", uz: "Buxoro → Xiva", zh: "布哈拉 → 希瓦", ko: "부하라 → 히바", de: "Buchara → Chiwa", fr: "Boukhara → Khiva", ja: "ブハラ → ヒヴァ", tr: "Buhara → Hive", ar: "بخارى ← خيوة" }),
  с("Хаст-Имам, Ташкент", { en: "Hast-Imam, Tashkent", uz: "Hazrati Imom, Toshkent", zh: "哈斯特伊玛目，塔什干", ko: "하스트 이맘, 타슈켄트", de: "Hast-Imam, Taschkent", fr: "Hast-Imam, Tachkent", ja: "ハズラティ・イマーム、タシケント", tr: "Hast-İmam, Taşkent", ar: "حضرة الإمام، طشقند" }),
  с("Регистан + медресе", { en: "Registan + madrasahs", uz: "Registon + madrasalar", zh: "雷吉斯坦 + 经学院", ko: "레기스탄 + 마드라사", de: "Registan + Medresen", fr: "Reguistan + madrasas", ja: "レギスタン + マドラサ", tr: "Registan + medreseler", ar: "ريغستان + المدارس" }),
  с("Минарет Калян, Бухара", { en: "Kalyan Minaret, Bukhara", uz: "Kalon minorasi, Buxoro", zh: "卡扬宣礼塔，布哈拉", ko: "칼란 미너렛, 부하라", de: "Kalyan-Minarett, Buchara", fr: "Minaret Kalian, Boukhara", ja: "カラーン・ミナレット、ブハラ", tr: "Kalyan Minaresi, Buhara", ar: "مئذنة كليان، بخارى" }),
  с("Мечеть Боло-Хауз", { en: "Bolo-Hauz Mosque", uz: "Bolo Hovuz masjidi", zh: "博洛豪兹清真寺", ko: "볼로하우즈 모스크", de: "Bolo-Hauz-Moschee", fr: "Mosquée Bolo-Haouz", ja: "ボロハウズ・モスク", tr: "Bolo-Havuz Camii", ar: "مسجد بولو حوض" }),
  с("Джума-мечеть Хивы", { en: "Juma Mosque of Khiva", uz: "Xiva Juma masjidi", zh: "希瓦聚礼清真寺", ko: "히바 주마 모스크", de: "Juma-Moschee von Chiwa", fr: "Mosquée Djouma de Khiva", ja: "ヒヴァのジュマ・モスク", tr: "Hive Cuma Camii", ar: "جامع خيوة" }),
  // ── Состояния погоды (статичный запас) ───────────────────────────
  с("Ясно", { en: "Clear", uz: "Ochiq", zh: "晴", ko: "맑음", de: "Klar", fr: "Dégagé", ja: "快晴", tr: "Açık", ar: "صافٍ" }),
  с("Малооблачно", { en: "Partly cloudy", uz: "Bir oz bulutli", zh: "少云", ko: "구름 조금", de: "Leicht bewölkt", fr: "Peu nuageux", ja: "薄曇り", tr: "Az bulutlu", ar: "غيوم قليلة" }),
  с("Зной", { en: "Hot", uz: "Jazirama", zh: "炎热", ko: "무더위", de: "Heiß", fr: "Chaleur", ja: "猛暑", tr: "Sıcak", ar: "حرّ" }),
  с("Знойно", { en: "Scorching", uz: "Jaziramali", zh: "酷热", ko: "폭염", de: "Glühend heiß", fr: "Torride", ja: "酷暑", tr: "Kavurucu", ar: "قائظ" }),
  с("Горный", { en: "Mountain", uz: "Togʻli", zh: "山地", ko: "산악", de: "Bergig", fr: "Montagnard", ja: "山岳", tr: "Dağlık", ar: "جبلي" }),
  с("Сухо", { en: "Dry", uz: "Quruq", zh: "干燥", ko: "건조", de: "Trocken", fr: "Sec", ja: "乾燥", tr: "Kuru", ar: "جاف" }),
  с("Переменная", { en: "Variable", uz: "Oʻzgaruvchan", zh: "多变", ko: "변덕", de: "Wechselhaft", fr: "Variable", ja: "変わりやすい", tr: "Değişken", ar: "متقلّب" }),
  с("Очень жарко", { en: "Very hot", uz: "Juda issiq", zh: "非常炎热", ko: "매우 더움", de: "Sehr heiß", fr: "Très chaud", ja: "非常に暑い", tr: "Çok sıcak", ar: "حارّ جداً" }),
  // ── Подписи городов ──────────────────────────────────────────────
  с("Город легенд и истории", { en: "City of legends and history", uz: "Afsona va tarix shahri", zh: "传奇与历史之城", ko: "전설과 역사의 도시", de: "Stadt der Legenden und Geschichte", fr: "Ville de légendes et d'histoire", ja: "伝説と歴史の街", tr: "Efsaneler ve tarih şehri", ar: "مدينة الأساطير والتاريخ" }),
  с("Древний город мира", { en: "An ancient city of the world", uz: "Dunyoning qadimiy shahri", zh: "世界古城", ko: "세계의 고대 도시", de: "Eine der ältesten Städte der Welt", fr: "Cité antique du monde", ja: "世界屈指の古都", tr: "Dünyanın kadim şehri", ar: "مدينة عريقة من مدن العالم" }),
  с("Природа и отдых", { en: "Nature and leisure", uz: "Tabiat va dam olish", zh: "自然与休闲", ko: "자연과 휴식", de: "Natur und Erholung", fr: "Nature et détente", ja: "自然と憩い", tr: "Doğa ve dinlence", ar: "طبيعة واستجمام" }),
  с("Жемчужина Хорезма", { en: "The pearl of Khorezm", uz: "Xorazm gavhari", zh: "花剌子模的明珠", ko: "호레즘의 진주", de: "Die Perle von Choresm", fr: "La perle du Khorezm", ja: "ホラズムの真珠", tr: "Harezm'in incisi", ar: "لؤلؤة خوارزم" }),
  // ── Рекламные подписи ────────────────────────────────────────────
  с("Скидка 20% при бронировании через UzUp", { en: "20% off when you book through UzUp", uz: "UzUp orqali bron qilsangiz 20% chegirma", zh: "通过 UzUp 预订享 8 折", ko: "UzUp로 예약 시 20% 할인", de: "20% Rabatt bei Buchung über UzUp", fr: "−20 % en réservant via UzUp", ja: "UzUp予約で20%オフ", tr: "UzUp üzerinden rezervasyonda %20 indirim", ar: "خصم 20% عند الحجز عبر UzUp" }),
  с("Лучший плов с 1978 года. Откройте для себя!", { en: "The best plov since 1978. Come and discover it!", uz: "1978 yildan beri eng zoʻr osh. Kashf eting!", zh: "自1978年以来的最佳抓饭，快来品尝！", ko: "1978년부터 이어온 최고의 플로프, 만나보세요!", de: "Der beste Plov seit 1978. Entdecken Sie ihn!", fr: "Le meilleur plov depuis 1978. Découvrez-le !", ja: "1978年以来の絶品プロフ。ぜひご賞味を！", tr: "1978'den beri en iyi plov. Keşfedin!", ar: "أفضل بلوف منذ 1978. اكتشفه!" }),
  с("Прямые рейсы из Самарканда. От $149", { en: "Direct flights from Samarkand. From $149", uz: "Samarqanddan toʻgʻridan-toʻgʻri reyslar. $149 dan", zh: "撒马尔罕直飞航班，$149 起", ko: "사마르칸트 직항. $149부터", de: "Direktflüge ab Samarkand. Ab 149 $", fr: "Vols directs depuis Samarcande. Dès 149 $", ja: "サマルカンド発の直行便。$149〜", tr: "Semerkant'tan direkt uçuşlar. $149'dan", ar: "رحلات مباشرة من سمرقند. من 149$" }),
  с("Аутентичные сувениры прямо от мастеров", { en: "Authentic souvenirs straight from the artisans", uz: "Ustalardan toʻgʻridan-toʻgʻri asl sovgʻalar", zh: "匠人手作的正宗纪念品", ko: "장인이 직접 만든 정통 기념품", de: "Authentische Souvenirs direkt vom Handwerker", fr: "Souvenirs authentiques directement des artisans", ja: "職人直伝の本物のみやげ", tr: "Doğrudan ustalardan özgün hediyelikler", ar: "تذكارات أصيلة مباشرة من الحرفيين" }),
  с("Трансфер аэропорт–город от $8", { en: "Airport–city transfer from $8", uz: "Aeroport–shahar transferi $8 dan", zh: "机场往返市区接送 $8 起", ko: "공항–시내 이동 $8부터", de: "Transfer Flughafen–Stadt ab 8 $", fr: "Transfert aéroport–ville dès 8 $", ja: "空港〜市内送迎 $8〜", tr: "Havalimanı–şehir transferi $8'den", ar: "نقل المطار–المدينة من 8$" }),
  // ── Планировщик: интересы, длительность, тема ────────────────────
  с("история", { en: "history", uz: "tarix", zh: "历史", ko: "역사", de: "Geschichte", fr: "histoire", ja: "歴史", tr: "tarih", ar: "تاريخ" }),
  с("мечети", { en: "mosques", uz: "masjidlar", zh: "清真寺", ko: "모스크", de: "Moscheen", fr: "mosquées", ja: "モスク", tr: "camiler", ar: "مساجد" }),
  с("еда", { en: "food", uz: "taom", zh: "美食", ko: "음식", de: "Essen", fr: "cuisine", ja: "料理", tr: "yemek", ar: "طعام" }),
  с("природа", { en: "nature", uz: "tabiat", zh: "自然", ko: "자연", de: "Natur", fr: "nature", ja: "自然", tr: "doğa", ar: "طبيعة" }),
  с("базары", { en: "bazaars", uz: "bozorlar", zh: "集市", ko: "시장", de: "Basare", fr: "bazars", ja: "バザール", tr: "pazarlar", ar: "أسواق" }),
  с("музеи", { en: "museums", uz: "muzeylar", zh: "博物馆", ko: "박물관", de: "Museen", fr: "musées", ja: "博物館", tr: "müzeler", ar: "متاحف" }),
  с("3 ч", { en: "3 h", uz: "3 soat", zh: "3 小时", ko: "3시간", de: "3 Std.", fr: "3 h", ja: "3時間", tr: "3 sa", ar: "3 ساعات" }),
  с("6 ч", { en: "6 h", uz: "6 soat", zh: "6 小时", ko: "6시간", de: "6 Std.", fr: "6 h", ja: "6時間", tr: "6 sa", ar: "6 ساعات" }),
  с("8 ч", { en: "8 h", uz: "8 soat", zh: "8 小时", ko: "8시간", de: "8 Std.", fr: "8 h", ja: "8時間", tr: "8 sa", ar: "8 ساعات" }),
  с("Весь день", { en: "All day", uz: "Kun boʻyi", zh: "全天", ko: "하루 종일", de: "Ganztags", fr: "Toute la journée", ja: "終日", tr: "Tüm gün", ar: "طوال اليوم" }),
  с("История + Архитектура + Кухня", { en: "History + Architecture + Cuisine", uz: "Tarix + Meʼmorchilik + Oshxona", zh: "历史 + 建筑 + 美食", ko: "역사 + 건축 + 미식", de: "Geschichte + Architektur + Küche", fr: "Histoire + Architecture + Cuisine", ja: "歴史 + 建築 + 料理", tr: "Tarih + Mimari + Mutfak", ar: "تاريخ + عمارة + مطبخ" }),
  с("Бесплатно", { en: "Free", uz: "Bepul", zh: "免费", ko: "무료", de: "Kostenlos", fr: "Gratuit", ja: "無料", tr: "Ücretsiz", ar: "مجاناً" }),
];

const СЛОВАРЬ: Map<string, Строка> = new Map(ЗАПИСИ);

/** Перевод строки содержимого. Нет перевода — возвращаем как есть. */
export function переведиКонтент(текст: string, locale: Locale): string {
  if (locale === "ru" || !текст) return текст;
  const п = СЛОВАРЬ.get(текст.trim());
  return п?.[locale] ?? текст;
}
